In [1]:
import os
import json
import sqlite3
import logging
from pipeline.schema_generation import schema_generation
from pipeline.schema_preprocess import schema_preprocess
from pipeline.data_rule_generation import data_rule_generation
from pipeline.data_generation import data_generation
from pipeline.temp_generation import temp_generation
from pipeline.ques_generation import ques_generation
from pipeline.ques_revision import ques_revision

In [2]:
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(message)s')

In [3]:
pipeline_config_path = './pipeline_configs.json'
engine_config_path = './engine_configs.json'
template_root = ''
output_root = '../output/'
result_root = '../result/'

In [4]:
try: 
    with open(pipeline_config_path, 'r') as file:
        pipeline_configs = json.load(file)
    logging.info('Load pipeline configurations successfully.')
    # logging.debug(pipeline_configs)
except Exception as e:
    logging.error(f'Load pipeline configurations failed: {e}')

2024-08-26 03:45:46,145 - Load pipeline configurations successfully.

## Schema Generation

In [5]:
config_schema_generation = pipeline_configs['schema_generation']

Run on all found databases

In [8]:
db_params_dict = {}
for filename in os.listdir(config_schema_generation['params_root']):
    if filename.endswith('.json'):
        db_name = os.path.splitext(filename)[0]
        try:
            schema_generation(db_name, config_schema_generation)
            logging.info(f'[Schema Generation]{db_name} success')
        except Exception as e:
            logging.error(f'[Schema Generation]{db_name} failed: {e}')

2024-08-25 03:19:15,423 - Starting database schema generation
2024-08-25 03:19:15,430 - Find db [UHC] parameter.

2024-08-25 03:19:15,431 - Template found
2024-08-25 03:19:15,431 - Requirements got
2024-08-25 03:19:15,432 - Human:
As a database engineer, design schema for a database called UHC.
Requirements:
The database is used for health care domain.
The database is used for university health center, collecting data of patients, doctors, etc.
Contains at least 5 tables.
Contains at least 50 columns in total.
Contains table patients(description: information of patients).
Table patients contains at least 20 columns.
Table patients contains column age(description: age of patients).
Contains table doctors.


For tables, give name and description in format:
{Table_name}: {Table_description}

For columns, give name, type and description in format:
({Column_type}){Column_name}: {Column_description}
Optional column types:
BOOLEAN: Column with boolean values (True / False) E.g. Active status
CHAR: Column with fixed-length string values E.g. Phone number
VARCHAR: Column with variable-length string values E.g. Name, Email address
INT: Column with integer values in specific range. E.g. Age
REAL: Column with float values in specific range. E.g. Income, Price
TEXT: Column with text values E.g. Instructions, Reasons, Descriptions
DATE: Column with values in format: YYYY-MM-DD
TIME: Column with values in format: HH:MM:SS
TIMESTAMP: Column with values in format: YYYY-MM-DD HH:MM:SS

For primary keys, column name should be followed by *
For foreign keys, referencing column should be followed by ({referenced table}.{referenced column})
When one column is primary key and foreign key at the same time, () should be followed by *, so * should always be followed by :

Output format (NO EXPLANATION! NO ANY OTHER OUTPUT!):

{Table1_name}: {Table1_description}
-({Column1.1_type}){Column1.1_name}*: {Column1.1_description}
-({Column1.2_type}){Column1.2_name}({Table2_name}.{Column2.1_name}): {Column1.2_description}

{Table2_name}: {Table2_description}
-({Column2.1_type}){Column2.1_name}*: {Column2.1_description}
-({Column2.2_type}){Column2.2_name}: {Column2.2_description}

2024-08-25 03:19:15,433 - Got LLM config
2024-08-25 03:19:15,434 - send prmopt to deepseek-coder
2024-08-25 03:19:15,435 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-25 03:19:15,658 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-25 03:19:53,267 - AI:
```
patients: Information of patients
-(INT)patient_id*: Unique identifier for each patient
-(VARCHAR)first_name: First name of the patient
-(VARCHAR)last_name: Last name of the patient
-(DATE)date_of_birth: Date of birth of the patient
-(INT)age: Age of the patient
-(VARCHAR)gender: Gender of the patient
-(VARCHAR)address: Address of the patient
-(CHAR)phone_number: Phone number of the patient
-(VARCHAR)email: Email address of the patient
-(VARCHAR)emergency_contact: Emergency contact name
-(CHAR)emergency_phone: Emergency contact phone number
-(VARCHAR)insurance_provider: Insurance provider name
-(VARCHAR)insurance_id: Insurance ID number
-(DATE)registration_date: Date of registration
-(BOOLEAN)active_status: Indicates if the patient is active
-(TEXT)medical_history: Summary of patient's medical history
-(VARCHAR)allergies: List of allergies
-(VARCHAR)medications: Current medications
-(VARCHAR)blood_type: Blood type of the patient
-(VARCHAR)preferred_language: Preferred language of the patient
-(VARCHAR)ethnicity: Ethnicity of the patient

doctors: Information of doctors
-(INT)doctor_id*: Unique identifier for each doctor
-(VARCHAR)first_name: First name of the doctor
-(VARCHAR)last_name: Last name of the doctor
-(DATE)date_of_birth: Date of birth of the doctor
-(VARCHAR)gender: Gender of the doctor
-(VARCHAR)specialization: Medical specialization
-(VARCHAR)address: Address of the doctor
-(CHAR)phone_number: Phone number of the doctor
-(VARCHAR)email: Email address of the doctor
-(VARCHAR)license_number: Medical license number
-(DATE)hire_date: Date of hire
-(BOOLEAN)active_status: Indicates if the doctor is active
-(TEXT)biography: Biography of the doctor
-(VARCHAR)languages: Languages spoken by the doctor

appointments: Information of appointments
-(INT)appointment_id*: Unique identifier for each appointment
-(INT)patient_id({patients}.patient_id): Reference to the patient
-(INT)doctor_id({doctors}.doctor_id): Reference to the doctor
-(TIMESTAMP)appointment_datetime: Date and time of the appointment
-(VARCHAR)appointment_type: Type of appointment (e.g., check-up, consultation)
-(TEXT)notes: Notes about the appointment
-(BOOLEAN)confirmed: Indicates if the appointment is confirmed

medical_records: Information of medical records
-(INT)record_id*: Unique identifier for each medical record
-(INT)patient_id({patients}.patient_id): Reference to the patient
-(INT)doctor_id({doctors}.doctor_id): Reference to the doctor
-(DATE)record_date: Date of the record creation
-(TEXT)diagnosis: Diagnosis details
-(TEXT)treatment: Treatment details
-(TEXT)prescriptions: Prescriptions given
-(TEXT)test_results: Results of medical tests

billing: Information of billing records
-(INT)billing_id*: Unique identifier for each billing record
-(INT)patient_id({patients}.patient_id): Reference to the patient
-(REAL)amount: Amount charged
-(DATE)billing_date: Date of billing
-(VARCHAR)payment_method: Method of payment
-(BOOLEAN)paid: Indicates if the bill is paid
-(TEXT)description: Description of the services provided
```
2024-08-25 03:19:53,272 - Run database creation SQL command:
CREATE TABLE `patients` ("patient_id" INT, "first_name" VARCHAR, "last_name" VARCHAR, "date_of_birth" DATE, "age" INT, "gender" VARCHAR, "address" VARCHAR, "phone_number" CHAR, "email" VARCHAR, "emergency_contact" VARCHAR, "emergency_phone" CHAR, "insurance_provider" VARCHAR, "insurance_id" VARCHAR, "registration_date" DATE, "active_status" BOOLEAN, "medical_history" TEXT, "allergies" VARCHAR, "medications" VARCHAR, "blood_type" VARCHAR, "preferred_language" VARCHAR, "ethnicity" VARCHAR, PRIMARY KEY ("patient_id"))
2024-08-25 03:19:53,277 - Run database creation SQL command:
CREATE TABLE `doctors` ("doctor_id" INT, "first_name" VARCHAR, "last_name" VARCHAR, "date_of_birth" DATE, "gender" VARCHAR, "specialization" VARCHAR, "address" VARCHAR, "phone_number" CHAR, "email" VARCHAR, "license_number" VARCHAR, "hire_date" DATE, "active_status" BOOLEAN, "biography" TEXT, "languages" VARCHAR, PRIMARY KEY ("doctor_id"))
2024-08-25 03:19:53,280 - Run database creation SQL command:
CREATE TABLE `appointments` ("appointment_id" INT, "appointment_datetime" TIMESTAMP, "appointment_type" VARCHAR, "notes" TEXT, "confirmed" BOOLEAN, PRIMARY KEY ("appointment_id"))
2024-08-25 03:19:53,283 - Run database creation SQL command:
CREATE TABLE `medical_records` ("record_id" INT, "record_date" DATE, "diagnosis" TEXT, "treatment" TEXT, "prescriptions" TEXT, "test_results" TEXT, PRIMARY KEY ("record_id"))
2024-08-25 03:19:53,287 - Run database creation SQL command:
CREATE TABLE `billing` ("billing_id" INT, "amount" REAL, "billing_date" DATE, "payment_method" VARCHAR, "paid" BOOLEAN, "description" TEXT, PRIMARY KEY ("billing_id"))
2024-08-25 03:19:53,290 - Schema generation success
2024-08-25 03:19:53,291 - [Schema Generation]UHC success

Run on one specific database

In [ ]:
db_name = 'UHC'
schema_generation(db_name, config_schema_generation)

## Schema Preprocess

In [5]:
config_schema_preprocess = pipeline_configs['schema_preprocess']

In [6]:
db_params_dict = {}
for filename in os.listdir(os.path.join(config_schema_preprocess['input_path'], 'schema_generation')):
    if filename.endswith('.sqlite'):
        db_name = os.path.splitext(filename)[0]
        try:
            schema_preprocess(db_name, config_schema_preprocess)
            logging.info(f'[Schema Preprocess]{db_name} success')
        except Exception as e:
            logging.error(f'[Schema Preprocess]{db_name} failed: {e}')

2024-08-26 00:19:33,879 - Starting schema preprocess
2024-08-26 00:19:33,882 - Schema got
2024-08-26 00:19:33,883 - {'frpm': {'description': '', 'attributes': {'CDSCode': {'description': '', 'type': 'TEXT'}, 'Academic Year': {'description': '', 'type': 'TEXT'}, 'County Code': {'description': '', 'type': 'TEXT'}, 'District Code': {'description': '', 'type': 'INTEGER'}, 'School Code': {'description': '', 'type': 'TEXT'}, 'County Name': {'description': '', 'type': 'TEXT'}, 'District Name': {'description': '', 'type': 'TEXT'}, 'School Name': {'description': '', 'type': 'TEXT'}, 'District Type': {'description': '', 'type': 'TEXT'}, 'School Type': {'description': '', 'type': 'TEXT'}, 'Educational Option Type': {'description': '', 'type': 'TEXT'}, 'NSLP Provision Status': {'description': '', 'type': 'TEXT'}, 'Charter School (Y/N)': {'description': '', 'type': 'INTEGER'}, 'Charter School Number': {'description': '', 'type': 'TEXT'}, 'Charter Funding Type': {'description': '', 'type': 'TEXT'}, 'IRC': {'description': '', 'type': 'INTEGER'}, 'Low Grade': {'description': '', 'type': 'TEXT'}, 'High Grade': {'description': '', 'type': 'TEXT'}, 'Enrollment (K-12)': {'description': '', 'type': 'REAL'}, 'Free Meal Count (K-12)': {'description': '', 'type': 'REAL'}, 'Percent (%) Eligible Free (K-12)': {'description': '', 'type': 'REAL'}, 'FRPM Count (K-12)': {'description': '', 'type': 'REAL'}, 'Percent (%) Eligible FRPM (K-12)': {'description': '', 'type': 'REAL'}, 'Enrollment (Ages 5-17)': {'description': '', 'type': 'REAL'}, 'Free Meal Count (Ages 5-17)': {'description': '', 'type': 'REAL'}, 'Percent (%) Eligible Free (Ages 5-17)': {'description': '', 'type': 'REAL'}, 'FRPM Count (Ages 5-17)': {'description': '', 'type': 'REAL'}, 'Percent (%) Eligible FRPM (Ages 5-17)': {'description': '', 'type': 'REAL'}, '2013-14 CALPADS Fall 1 Certification Status': {'description': '', 'type': 'INTEGER'}}, 'primary_keys': ['CDSCode'], 'foreign_keys': {'CDSCode': {'referenced_table': 'schools', 'referenced_column': 'CDSCode'}}}, 'satscores': {'description': '', 'attributes': {'cds': {'description': '', 'type': 'TEXT'}, 'rtype': {'description': '', 'type': 'TEXT'}, 'sname': {'description': '', 'type': 'TEXT'}, 'dname': {'description': '', 'type': 'TEXT'}, 'cname': {'description': '', 'type': 'TEXT'}, 'enroll12': {'description': '', 'type': 'INTEGER'}, 'NumTstTakr': {'description': '', 'type': 'INTEGER'}, 'AvgScrRead': {'description': '', 'type': 'INTEGER'}, 'AvgScrMath': {'description': '', 'type': 'INTEGER'}, 'AvgScrWrite': {'description': '', 'type': 'INTEGER'}, 'NumGE1500': {'description': '', 'type': 'INTEGER'}}, 'primary_keys': ['cds'], 'foreign_keys': {'cds': {'referenced_table': 'schools', 'referenced_column': 'CDSCode'}}}, 'schools': {'description': '', 'attributes': {'CDSCode': {'description': '', 'type': 'TEXT'}, 'NCESDist': {'description': '', 'type': 'TEXT'}, 'NCESSchool': {'description': '', 'type': 'TEXT'}, 'StatusType': {'description': '', 'type': 'TEXT'}, 'County': {'description': '', 'type': 'TEXT'}, 'District': {'description': '', 'type': 'TEXT'}, 'School': {'description': '', 'type': 'TEXT'}, 'Street': {'description': '', 'type': 'TEXT'}, 'StreetAbr': {'description': '', 'type': 'TEXT'}, 'City': {'description': '', 'type': 'TEXT'}, 'Zip': {'description': '', 'type': 'TEXT'}, 'State': {'description': '', 'type': 'TEXT'}, 'MailStreet': {'description': '', 'type': 'TEXT'}, 'MailStrAbr': {'description': '', 'type': 'TEXT'}, 'MailCity': {'description': '', 'type': 'TEXT'}, 'MailZip': {'description': '', 'type': 'TEXT'}, 'MailState': {'description': '', 'type': 'TEXT'}, 'Phone': {'description': '', 'type': 'TEXT'}, 'Ext': {'description': '', 'type': 'TEXT'}, 'Website': {'description': '', 'type': 'TEXT'}, 'OpenDate': {'description': '', 'type': 'DATE'}, 'ClosedDate': {'description': '', 'type': 'DATE'}, 'Charter': {'description': '', 'type': 'INTEGER'}, 'CharterNum': {'description': '', 'type': 'TEXT'}, 'FundingType': {'description': '', 'type': 'TEXT'}, 'DOC': {'description': '', 'type': 'TEXT'}, 'DOCType': {'description': '', 'type': 'TEXT'}, 'SOC': {'description': '', 'type': 'TEXT'}, 'SOCType': {'description': '', 'type': 'TEXT'}, 'EdOpsCode': {'description': '', 'type': 'TEXT'}, 'EdOpsName': {'description': '', 'type': 'TEXT'}, 'EILCode': {'description': '', 'type': 'TEXT'}, 'EILName': {'description': '', 'type': 'TEXT'}, 'GSoffered': {'description': '', 'type': 'TEXT'}, 'GSserved': {'description': '', 'type': 'TEXT'}, 'Virtual': {'description': '', 'type': 'TEXT'}, 'Magnet': {'description': '', 'type': 'INTEGER'}, 'Latitude': {'description': '', 'type': 'REAL'}, 'Longitude': {'description': '', 'type': 'REAL'}, 'AdmFName1': {'description': '', 'type': 'TEXT'}, 'AdmLName1': {'description': '', 'type': 'TEXT'}, 'AdmEmail1': {'description': '', 'type': 'TEXT'}, 'AdmFName2': {'description': '', 'type': 'TEXT'}, 'AdmLName2': {'description': '', 'type': 'TEXT'}, 'AdmEmail2': {'description': '', 'type': 'TEXT'}, 'AdmFName3': {'description': '', 'type': 'TEXT'}, 'AdmLName3': {'description': '', 'type': 'TEXT'}, 'AdmEmail3': {'description': '', 'type': 'TEXT'}, 'LastUpdate': {'description': '', 'type': 'DATE'}}, 'primary_keys': ['CDSCode'], 'foreign_keys': {}}}
2024-08-26 00:19:33,890 - [Schema Preprocess]california_schools success
2024-08-26 00:19:33,892 - Starting schema preprocess
2024-08-26 00:19:33,897 - Schema got
2024-08-26 00:19:33,899 - {'patients': {'description': '', 'attributes': {'patient_id': {'description': '', 'type': 'INT'}, 'first_name': {'description': '', 'type': 'VARCHAR'}, 'last_name': {'description': '', 'type': 'VARCHAR'}, 'date_of_birth': {'description': '', 'type': 'DATE'}, 'age': {'description': '', 'type': 'INT'}, 'gender': {'description': '', 'type': 'VARCHAR'}, 'address': {'description': '', 'type': 'VARCHAR'}, 'phone_number': {'description': '', 'type': 'CHAR'}, 'email': {'description': '', 'type': 'VARCHAR'}, 'emergency_contact': {'description': '', 'type': 'VARCHAR'}, 'emergency_phone': {'description': '', 'type': 'CHAR'}, 'insurance_provider': {'description': '', 'type': 'VARCHAR'}, 'insurance_id': {'description': '', 'type': 'VARCHAR'}, 'registration_date': {'description': '', 'type': 'DATE'}, 'active_status': {'description': '', 'type': 'BOOLEAN'}, 'medical_history': {'description': '', 'type': 'TEXT'}, 'allergies': {'description': '', 'type': 'VARCHAR'}, 'medications': {'description': '', 'type': 'VARCHAR'}, 'blood_type': {'description': '', 'type': 'VARCHAR'}, 'preferred_language': {'description': '', 'type': 'VARCHAR'}, 'ethnicity': {'description': '', 'type': 'VARCHAR'}}, 'primary_keys': ['patient_id'], 'foreign_keys': {}}, 'doctors': {'description': '', 'attributes': {'doctor_id': {'description': '', 'type': 'INT'}, 'first_name': {'description': '', 'type': 'VARCHAR'}, 'last_name': {'description': '', 'type': 'VARCHAR'}, 'date_of_birth': {'description': '', 'type': 'DATE'}, 'gender': {'description': '', 'type': 'VARCHAR'}, 'specialization': {'description': '', 'type': 'VARCHAR'}, 'address': {'description': '', 'type': 'VARCHAR'}, 'phone_number': {'description': '', 'type': 'CHAR'}, 'email': {'description': '', 'type': 'VARCHAR'}, 'license_number': {'description': '', 'type': 'VARCHAR'}, 'hire_date': {'description': '', 'type': 'DATE'}, 'active_status': {'description': '', 'type': 'BOOLEAN'}, 'biography': {'description': '', 'type': 'TEXT'}, 'languages': {'description': '', 'type': 'VARCHAR'}}, 'primary_keys': ['doctor_id'], 'foreign_keys': {}}, 'appointments': {'description': '', 'attributes': {'appointment_id': {'description': '', 'type': 'INT'}, 'appointment_datetime': {'description': '', 'type': 'TIMESTAMP'}, 'appointment_type': {'description': '', 'type': 'VARCHAR'}, 'notes': {'description': '', 'type': 'TEXT'}, 'confirmed': {'description': '', 'type': 'BOOLEAN'}}, 'primary_keys': ['appointment_id'], 'foreign_keys': {}}, 'medical_records': {'description': '', 'attributes': {'record_id': {'description': '', 'type': 'INT'}, 'record_date': {'description': '', 'type': 'DATE'}, 'diagnosis': {'description': '', 'type': 'TEXT'}, 'treatment': {'description': '', 'type': 'TEXT'}, 'prescriptions': {'description': '', 'type': 'TEXT'}, 'test_results': {'description': '', 'type': 'TEXT'}}, 'primary_keys': ['record_id'], 'foreign_keys': {}}, 'billing': {'description': '', 'attributes': {'billing_id': {'description': '', 'type': 'INT'}, 'amount': {'description': '', 'type': 'REAL'}, 'billing_date': {'description': '', 'type': 'DATE'}, 'payment_method': {'description': '', 'type': 'VARCHAR'}, 'paid': {'description': '', 'type': 'BOOLEAN'}, 'description': {'description': '', 'type': 'TEXT'}}, 'primary_keys': ['billing_id'], 'foreign_keys': {}}}
2024-08-26 00:19:33,909 - [Schema Preprocess]UHC success

In [7]:
db_name = 'california_schools'
schema_preprocess(db_name, config_schema_preprocess)

2024-08-18 01:55:20,601 - Starting schema preprocess
2024-08-18 01:55:20,602 - Schema got
2024-08-18 01:55:20,603 - {'frpm': {'description': '', 'attributes': {'CDSCode': {'description': '', 'type': 'TEXT'}, 'Academic Year': {'description': '', 'type': 'TEXT'}, 'County Code': {'description': '', 'type': 'TEXT'}, 'District Code': {'description': '', 'type': 'INTEGER'}, 'School Code': {'description': '', 'type': 'TEXT'}, 'County Name': {'description': '', 'type': 'TEXT'}, 'District Name': {'description': '', 'type': 'TEXT'}, 'School Name': {'description': '', 'type': 'TEXT'}, 'District Type': {'description': '', 'type': 'TEXT'}, 'School Type': {'description': '', 'type': 'TEXT'}, 'Educational Option Type': {'description': '', 'type': 'TEXT'}, 'NSLP Provision Status': {'description': '', 'type': 'TEXT'}, 'Charter School (Y/N)': {'description': '', 'type': 'INTEGER'}, 'Charter School Number': {'description': '', 'type': 'TEXT'}, 'Charter Funding Type': {'description': '', 'type': 'TEXT'}, 'IRC': {'description': '', 'type': 'INTEGER'}, 'Low Grade': {'description': '', 'type': 'TEXT'}, 'High Grade': {'description': '', 'type': 'TEXT'}, 'Enrollment (K-12)': {'description': '', 'type': 'REAL'}, 'Free Meal Count (K-12)': {'description': '', 'type': 'REAL'}, 'Percent (%) Eligible Free (K-12)': {'description': '', 'type': 'REAL'}, 'FRPM Count (K-12)': {'description': '', 'type': 'REAL'}, 'Percent (%) Eligible FRPM (K-12)': {'description': '', 'type': 'REAL'}, 'Enrollment (Ages 5-17)': {'description': '', 'type': 'REAL'}, 'Free Meal Count (Ages 5-17)': {'description': '', 'type': 'REAL'}, 'Percent (%) Eligible Free (Ages 5-17)': {'description': '', 'type': 'REAL'}, 'FRPM Count (Ages 5-17)': {'description': '', 'type': 'REAL'}, 'Percent (%) Eligible FRPM (Ages 5-17)': {'description': '', 'type': 'REAL'}, '2013-14 CALPADS Fall 1 Certification Status': {'description': '', 'type': 'INTEGER'}}, 'primary_keys': ['CDSCode'], 'foreign_keys': [{'column': 'CDSCode', 'referenced_table': 'schools', 'referenced_column': 'CDSCode'}]}, 'satscores': {'description': '', 'attributes': {'cds': {'description': '', 'type': 'TEXT'}, 'rtype': {'description': '', 'type': 'TEXT'}, 'sname': {'description': '', 'type': 'TEXT'}, 'dname': {'description': '', 'type': 'TEXT'}, 'cname': {'description': '', 'type': 'TEXT'}, 'enroll12': {'description': '', 'type': 'INTEGER'}, 'NumTstTakr': {'description': '', 'type': 'INTEGER'}, 'AvgScrRead': {'description': '', 'type': 'INTEGER'}, 'AvgScrMath': {'description': '', 'type': 'INTEGER'}, 'AvgScrWrite': {'description': '', 'type': 'INTEGER'}, 'NumGE1500': {'description': '', 'type': 'INTEGER'}}, 'primary_keys': ['cds'], 'foreign_keys': [{'column': 'cds', 'referenced_table': 'schools', 'referenced_column': 'CDSCode'}]}, 'schools': {'description': '', 'attributes': {'CDSCode': {'description': '', 'type': 'TEXT'}, 'NCESDist': {'description': '', 'type': 'TEXT'}, 'NCESSchool': {'description': '', 'type': 'TEXT'}, 'StatusType': {'description': '', 'type': 'TEXT'}, 'County': {'description': '', 'type': 'TEXT'}, 'District': {'description': '', 'type': 'TEXT'}, 'School': {'description': '', 'type': 'TEXT'}, 'Street': {'description': '', 'type': 'TEXT'}, 'StreetAbr': {'description': '', 'type': 'TEXT'}, 'City': {'description': '', 'type': 'TEXT'}, 'Zip': {'description': '', 'type': 'TEXT'}, 'State': {'description': '', 'type': 'TEXT'}, 'MailStreet': {'description': '', 'type': 'TEXT'}, 'MailStrAbr': {'description': '', 'type': 'TEXT'}, 'MailCity': {'description': '', 'type': 'TEXT'}, 'MailZip': {'description': '', 'type': 'TEXT'}, 'MailState': {'description': '', 'type': 'TEXT'}, 'Phone': {'description': '', 'type': 'TEXT'}, 'Ext': {'description': '', 'type': 'TEXT'}, 'Website': {'description': '', 'type': 'TEXT'}, 'OpenDate': {'description': '', 'type': 'DATE'}, 'ClosedDate': {'description': '', 'type': 'DATE'}, 'Charter': {'description': '', 'type': 'INTEGER'}, 'CharterNum': {'description': '', 'type': 'TEXT'}, 'FundingType': {'description': '', 'type': 'TEXT'}, 'DOC': {'description': '', 'type': 'TEXT'}, 'DOCType': {'description': '', 'type': 'TEXT'}, 'SOC': {'description': '', 'type': 'TEXT'}, 'SOCType': {'description': '', 'type': 'TEXT'}, 'EdOpsCode': {'description': '', 'type': 'TEXT'}, 'EdOpsName': {'description': '', 'type': 'TEXT'}, 'EILCode': {'description': '', 'type': 'TEXT'}, 'EILName': {'description': '', 'type': 'TEXT'}, 'GSoffered': {'description': '', 'type': 'TEXT'}, 'GSserved': {'description': '', 'type': 'TEXT'}, 'Virtual': {'description': '', 'type': 'TEXT'}, 'Magnet': {'description': '', 'type': 'INTEGER'}, 'Latitude': {'description': '', 'type': 'REAL'}, 'Longitude': {'description': '', 'type': 'REAL'}, 'AdmFName1': {'description': '', 'type': 'TEXT'}, 'AdmLName1': {'description': '', 'type': 'TEXT'}, 'AdmEmail1': {'description': '', 'type': 'TEXT'}, 'AdmFName2': {'description': '', 'type': 'TEXT'}, 'AdmLName2': {'description': '', 'type': 'TEXT'}, 'AdmEmail2': {'description': '', 'type': 'TEXT'}, 'AdmFName3': {'description': '', 'type': 'TEXT'}, 'AdmLName3': {'description': '', 'type': 'TEXT'}, 'AdmEmail3': {'description': '', 'type': 'TEXT'}, 'LastUpdate': {'description': '', 'type': 'DATE'}}, 'primary_keys': ['CDSCode'], 'foreign_keys': []}}

## Data Rule Generation

In [5]:
config_data_rule_generation = pipeline_configs['data_rule_generation']

In [6]:
db_name = 'california_schools'
data_rule_generation(db_name, config_data_rule_generation)

2024-08-26 03:31:56,506 - Starting database data rule generation
2024-08-26 03:31:56,508 - california_schools SCHEMA loaded
2024-08-26 03:31:56,510 - california_schools REFERENCED COLS got
2024-08-26 03:31:56,511 - california_schools SCHEMA PROMPT loaded
2024-08-26 03:31:56,512 - Template found
2024-08-26 03:31:56,513 - Template found
2024-08-26 03:31:56,514 - Template found
2024-08-26 03:31:56,514 - Human:
As a database engineer, examine given schema and point out all IDENTIFIER columns in the schema.

IDENTIFIER: Column with auto-incremented values used to uniquely identify records in this table

Output format (NO EXPLANATION! NO ANY OTHER OUTPUT!):
table1.identifier1
table1.identifier2
table2.identifier1
...
====================
E.g.
Schema:

CREATE TABLE `students` (
    `student_id` INT,
    `name` VARCHAR,
    PRIMARY KEY (`student_id`)
);

CREATE TABLE teachers (
    `teacher_id` INT,
    `name` VARCHAR,
    PRIMARY KEY (`teacher_id`)
);

CREATE TABLE courses (
    `course_id` INT,
    `teacher_id` INT,
    `course_name` VARCHAR,
    PRIMARY KEY (`course_id`)
);

CREATE TABLE scores (
    `student_id` INT,
    `course_id` INT,
    `score` REAL,
    PRIMARY KEY (`student_id`, `course_id`)
);

Identifier:
students.student_id
teachers.teacher_id
courses.course_id
courses.teacher_id
scores.student_id
scores.course_id
====================
Schema:

CREATE TABLE frpm (
    CDSCode TEXT,
    Academic Year TEXT,
    County Code TEXT,
    District Code INTEGER,
    School Code TEXT,
    County Name TEXT,
    District Name TEXT,
    School Name TEXT,
    District Type TEXT,
    School Type TEXT,
    Educational Option Type TEXT,
    NSLP Provision Status TEXT,
    Charter School (Y/N) INTEGER,
    Charter School Number TEXT,
    Charter Funding Type TEXT,
    IRC INTEGER,
    Low Grade TEXT,
    High Grade TEXT,
    Enrollment (K-12) REAL,
    Free Meal Count (K-12) REAL,
    Percent (%) Eligible Free (K-12) REAL,
    FRPM Count (K-12) REAL,
    Percent (%) Eligible FRPM (K-12) REAL,
    Enrollment (Ages 5-17) REAL,
    Free Meal Count (Ages 5-17) REAL,
    Percent (%) Eligible Free (Ages 5-17) REAL,
    FRPM Count (Ages 5-17) REAL,
    Percent (%) Eligible FRPM (Ages 5-17) REAL,
    2013-14 CALPADS Fall 1 Certification Status INTEGER,
    PRIMARY KEY (CDSCode),
    FOREIGN KEY (CDSCode) REFERENCES schools (CDSCode)
);
CREATE TABLE satscores (
    cds TEXT,
    rtype TEXT,
    sname TEXT,
    dname TEXT,
    cname TEXT,
    enroll12 INTEGER,
    NumTstTakr INTEGER,
    AvgScrRead INTEGER,
    AvgScrMath INTEGER,
    AvgScrWrite INTEGER,
    NumGE1500 INTEGER,
    PRIMARY KEY (cds),
    FOREIGN KEY (cds) REFERENCES schools (CDSCode)
);
CREATE TABLE schools (
    CDSCode TEXT,
    NCESDist TEXT,
    NCESSchool TEXT,
    StatusType TEXT,
    County TEXT,
    District TEXT,
    School TEXT,
    Street TEXT,
    StreetAbr TEXT,
    City TEXT,
    Zip TEXT,
    State TEXT,
    MailStreet TEXT,
    MailStrAbr TEXT,
    MailCity TEXT,
    MailZip TEXT,
    MailState TEXT,
    Phone TEXT,
    Ext TEXT,
    Website TEXT,
    OpenDate DATE,
    ClosedDate DATE,
    Charter INTEGER,
    CharterNum TEXT,
    FundingType TEXT,
    DOC TEXT,
    DOCType TEXT,
    SOC TEXT,
    SOCType TEXT,
    EdOpsCode TEXT,
    EdOpsName TEXT,
    EILCode TEXT,
    EILName TEXT,
    GSoffered TEXT,
    GSserved TEXT,
    Virtual TEXT,
    Magnet INTEGER,
    Latitude REAL,
    Longitude REAL,
    AdmFName1 TEXT,
    AdmLName1 TEXT,
    AdmEmail1 TEXT,
    AdmFName2 TEXT,
    AdmLName2 TEXT,
    AdmEmail2 TEXT,
    AdmFName3 TEXT,
    AdmLName3 TEXT,
    AdmEmail3 TEXT,
    LastUpdate DATE,
    PRIMARY KEY (CDSCode)
);

Identifier:

2024-08-26 03:31:56,516 - Got LLM config
2024-08-26 03:31:56,517 - send prmopt to deepseek-coder
2024-08-26 03:31:56,520 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-26 03:31:56,812 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-26 03:31:57,844 - AI:
frpm.CDSCode
satscores.cds
schools.CDSCode
2024-08-26 03:31:57,858 - Human:
As a database engineer, judge whether a specific column in database is a categorical column with given information. If it is, give all possible categories for this column.

Output format (NO EXPLANATION! NO ANY OTHER OUTPUT!):
Category1, Category2, ...

Or, this column is not categorical column:
Output format:
0
====================
E.g.
Database name: schools
Table name: teachers
Column name: gender
Schema:

CREATE TABLE `teachers` (
    `teacher_id` INT,
    `gender` VARCHAR
)

Output:
Male, Female, Other

Database name: schools
Table name: teachers
Column name: first_name
Schema:

CREATE TABLE `teachers` (
    `teacher_id` INT,
    `first_name` VARCHAR
)

Output:
0
====================
Database name: california_schools
Table name: frpm
Column name: Academic Year
Schema:

CREATE TABLE frpm (
    CDSCode TEXT,
    Academic Year TEXT,
    County Code TEXT,
    District Code INTEGER,
    School Code TEXT,
    County Name TEXT,
    District Name TEXT,
    School Name TEXT,
    District Type TEXT,
    School Type TEXT,
    Educational Option Type TEXT,
    NSLP Provision Status TEXT,
    Charter School (Y/N) INTEGER,
    Charter School Number TEXT,
    Charter Funding Type TEXT,
    IRC INTEGER,
    Low Grade TEXT,
    High Grade TEXT,
    Enrollment (K-12) REAL,
    Free Meal Count (K-12) REAL,
    Percent (%) Eligible Free (K-12) REAL,
    FRPM Count (K-12) REAL,
    Percent (%) Eligible FRPM (K-12) REAL,
    Enrollment (Ages 5-17) REAL,
    Free Meal Count (Ages 5-17) REAL,
    Percent (%) Eligible Free (Ages 5-17) REAL,
    FRPM Count (Ages 5-17) REAL,
    Percent (%) Eligible FRPM (Ages 5-17) REAL,
    2013-14 CALPADS Fall 1 Certification Status INTEGER,
    PRIMARY KEY (CDSCode),
    FOREIGN KEY (CDSCode) REFERENCES schools (CDSCode)
);
There are 1 unique values in this column right now.
Example Values: 2014-2015

2024-08-26 03:31:57,860 - Got LLM config
2024-08-26 03:31:57,860 - send prmopt to deepseek-coder
2024-08-26 03:31:57,862 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-26 03:31:58,058 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-26 03:31:58,712 - AI:
2014-2015
2024-08-26 03:31:58,760 - Human:
As a database engineer, judge whether a specific column in database is a categorical column with given information. If it is, give all possible categories for this column.

Output format (NO EXPLANATION! NO ANY OTHER OUTPUT!):
Category1, Category2, ...

Or, this column is not categorical column:
Output format:
0
====================
E.g.
Database name: schools
Table name: teachers
Column name: gender
Schema:

CREATE TABLE `teachers` (
    `teacher_id` INT,
    `gender` VARCHAR
)

Output:
Male, Female, Other

Database name: schools
Table name: teachers
Column name: first_name
Schema:

CREATE TABLE `teachers` (
    `teacher_id` INT,
    `first_name` VARCHAR
)

Output:
0
====================
Database name: california_schools
Table name: frpm
Column name: District Type
Schema:

CREATE TABLE frpm (
    CDSCode TEXT,
    Academic Year TEXT,
    County Code TEXT,
    District Code INTEGER,
    School Code TEXT,
    County Name TEXT,
    District Name TEXT,
    School Name TEXT,
    District Type TEXT,
    School Type TEXT,
    Educational Option Type TEXT,
    NSLP Provision Status TEXT,
    Charter School (Y/N) INTEGER,
    Charter School Number TEXT,
    Charter Funding Type TEXT,
    IRC INTEGER,
    Low Grade TEXT,
    High Grade TEXT,
    Enrollment (K-12) REAL,
    Free Meal Count (K-12) REAL,
    Percent (%) Eligible Free (K-12) REAL,
    FRPM Count (K-12) REAL,
    Percent (%) Eligible FRPM (K-12) REAL,
    Enrollment (Ages 5-17) REAL,
    Free Meal Count (Ages 5-17) REAL,
    Percent (%) Eligible Free (Ages 5-17) REAL,
    FRPM Count (Ages 5-17) REAL,
    Percent (%) Eligible FRPM (Ages 5-17) REAL,
    2013-14 CALPADS Fall 1 Certification Status INTEGER,
    PRIMARY KEY (CDSCode),
    FOREIGN KEY (CDSCode) REFERENCES schools (CDSCode)
);
There are 8 unique values in this column right now.
Example Values: County Office of Education (COE), State Special Schools, Unified School District, Elementary School District, High School District

2024-08-26 03:31:58,764 - Got LLM config
2024-08-26 03:31:58,765 - send prmopt to deepseek-coder
2024-08-26 03:31:58,767 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-26 03:31:58,979 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-26 03:32:00,864 - AI:
County Office of Education (COE), State Special Schools, Unified School District, Elementary School District, High School District, Junior High School District, K-12 District, Community Day School
2024-08-26 03:32:00,871 - Human:
As a database engineer, judge whether a specific column in database is a categorical column with given information. If it is, give all possible categories for this column.

Output format (NO EXPLANATION! NO ANY OTHER OUTPUT!):
Category1, Category2, ...

Or, this column is not categorical column:
Output format:
0
====================
E.g.
Database name: schools
Table name: teachers
Column name: gender
Schema:

CREATE TABLE `teachers` (
    `teacher_id` INT,
    `gender` VARCHAR
)

Output:
Male, Female, Other

Database name: schools
Table name: teachers
Column name: first_name
Schema:

CREATE TABLE `teachers` (
    `teacher_id` INT,
    `first_name` VARCHAR
)

Output:
0
====================
Database name: california_schools
Table name: frpm
Column name: School Type
Schema:

CREATE TABLE frpm (
    CDSCode TEXT,
    Academic Year TEXT,
    County Code TEXT,
    District Code INTEGER,
    School Code TEXT,
    County Name TEXT,
    District Name TEXT,
    School Name TEXT,
    District Type TEXT,
    School Type TEXT,
    Educational Option Type TEXT,
    NSLP Provision Status TEXT,
    Charter School (Y/N) INTEGER,
    Charter School Number TEXT,
    Charter Funding Type TEXT,
    IRC INTEGER,
    Low Grade TEXT,
    High Grade TEXT,
    Enrollment (K-12) REAL,
    Free Meal Count (K-12) REAL,
    Percent (%) Eligible Free (K-12) REAL,
    FRPM Count (K-12) REAL,
    Percent (%) Eligible FRPM (K-12) REAL,
    Enrollment (Ages 5-17) REAL,
    Free Meal Count (Ages 5-17) REAL,
    Percent (%) Eligible Free (Ages 5-17) REAL,
    FRPM Count (Ages 5-17) REAL,
    Percent (%) Eligible FRPM (Ages 5-17) REAL,
    2013-14 CALPADS Fall 1 Certification Status INTEGER,
    PRIMARY KEY (CDSCode),
    FOREIGN KEY (CDSCode) REFERENCES schools (CDSCode)
);
There are 17 unique values in this column right now.
Example Values: K-12 Schools (Public), High Schools (Public), Elementary Schools (Public), Juvenile Court Schools, County Community

2024-08-26 03:32:00,872 - Got LLM config
2024-08-26 03:32:00,873 - send prmopt to deepseek-coder
2024-08-26 03:32:00,874 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-26 03:32:01,059 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-26 03:32:02,353 - AI:
K-12 Schools (Public), High Schools (Public), Elementary Schools (Public), Juvenile Court Schools, County Community
2024-08-26 03:32:02,360 - Human:
As a database engineer, judge whether a specific column in database is a categorical column with given information. If it is, give all possible categories for this column.

Output format (NO EXPLANATION! NO ANY OTHER OUTPUT!):
Category1, Category2, ...

Or, this column is not categorical column:
Output format:
0
====================
E.g.
Database name: schools
Table name: teachers
Column name: gender
Schema:

CREATE TABLE `teachers` (
    `teacher_id` INT,
    `gender` VARCHAR
)

Output:
Male, Female, Other

Database name: schools
Table name: teachers
Column name: first_name
Schema:

CREATE TABLE `teachers` (
    `teacher_id` INT,
    `first_name` VARCHAR
)

Output:
0
====================
Database name: california_schools
Table name: frpm
Column name: Educational Option Type
Schema:

CREATE TABLE frpm (
    CDSCode TEXT,
    Academic Year TEXT,
    County Code TEXT,
    District Code INTEGER,
    School Code TEXT,
    County Name TEXT,
    District Name TEXT,
    School Name TEXT,
    District Type TEXT,
    School Type TEXT,
    Educational Option Type TEXT,
    NSLP Provision Status TEXT,
    Charter School (Y/N) INTEGER,
    Charter School Number TEXT,
    Charter Funding Type TEXT,
    IRC INTEGER,
    Low Grade TEXT,
    High Grade TEXT,
    Enrollment (K-12) REAL,
    Free Meal Count (K-12) REAL,
    Percent (%) Eligible Free (K-12) REAL,
    FRPM Count (K-12) REAL,
    Percent (%) Eligible FRPM (K-12) REAL,
    Enrollment (Ages 5-17) REAL,
    Free Meal Count (Ages 5-17) REAL,
    Percent (%) Eligible Free (Ages 5-17) REAL,
    FRPM Count (Ages 5-17) REAL,
    Percent (%) Eligible FRPM (Ages 5-17) REAL,
    2013-14 CALPADS Fall 1 Certification Status INTEGER,
    PRIMARY KEY (CDSCode),
    FOREIGN KEY (CDSCode) REFERENCES schools (CDSCode)
);
There are 12 unique values in this column right now.
Example Values: Traditional, Juvenile Court School, County Community School, State Special School, Alternative School of Choice

2024-08-26 03:32:02,362 - Got LLM config
2024-08-26 03:32:02,362 - send prmopt to deepseek-coder
2024-08-26 03:32:02,363 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-26 03:32:02,560 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-26 03:32:04,826 - AI:
Traditional, Juvenile Court School, County Community School, State Special School, Alternative School of Choice, Opportunity School, Continuation School, Alternative Education School, Special Education School, Regional Occupational Center/Program, Detention Center, Hospital/Home/Institution
2024-08-26 03:32:04,837 - Human:
As a database engineer, judge whether a specific column in database is a categorical column with given information. If it is, give all possible categories for this column.

Output format (NO EXPLANATION! NO ANY OTHER OUTPUT!):
Category1, Category2, ...

Or, this column is not categorical column:
Output format:
0
====================
E.g.
Database name: schools
Table name: teachers
Column name: gender
Schema:

CREATE TABLE `teachers` (
    `teacher_id` INT,
    `gender` VARCHAR
)

Output:
Male, Female, Other

Database name: schools
Table name: teachers
Column name: first_name
Schema:

CREATE TABLE `teachers` (
    `teacher_id` INT,
    `first_name` VARCHAR
)

Output:
0
====================
Database name: california_schools
Table name: frpm
Column name: NSLP Provision Status
Schema:

CREATE TABLE frpm (
    CDSCode TEXT,
    Academic Year TEXT,
    County Code TEXT,
    District Code INTEGER,
    School Code TEXT,
    County Name TEXT,
    District Name TEXT,
    School Name TEXT,
    District Type TEXT,
    School Type TEXT,
    Educational Option Type TEXT,
    NSLP Provision Status TEXT,
    Charter School (Y/N) INTEGER,
    Charter School Number TEXT,
    Charter Funding Type TEXT,
    IRC INTEGER,
    Low Grade TEXT,
    High Grade TEXT,
    Enrollment (K-12) REAL,
    Free Meal Count (K-12) REAL,
    Percent (%) Eligible Free (K-12) REAL,
    FRPM Count (K-12) REAL,
    Percent (%) Eligible FRPM (K-12) REAL,
    Enrollment (Ages 5-17) REAL,
    Free Meal Count (Ages 5-17) REAL,
    Percent (%) Eligible Free (Ages 5-17) REAL,
    FRPM Count (Ages 5-17) REAL,
    Percent (%) Eligible FRPM (Ages 5-17) REAL,
    2013-14 CALPADS Fall 1 Certification Status INTEGER,
    PRIMARY KEY (CDSCode),
    FOREIGN KEY (CDSCode) REFERENCES schools (CDSCode)
);
There are 7 unique values in this column right now.
Example Values: None, Breakfast Provision 2, Provision 2, CEP, Lunch Provision 2

2024-08-26 03:32:04,838 - Got LLM config
2024-08-26 03:32:04,838 - send prmopt to deepseek-coder
2024-08-26 03:32:04,840 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-26 03:32:05,047 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-26 03:32:06,156 - AI:
None, Breakfast Provision 2, Provision 2, CEP, Lunch Provision 2
2024-08-26 03:32:06,168 - Human:
As a database engineer, judge whether a specific column in database is a categorical column with given information. If it is, give all possible categories for this column.

Output format (NO EXPLANATION! NO ANY OTHER OUTPUT!):
Category1, Category2, ...

Or, this column is not categorical column:
Output format:
0
====================
E.g.
Database name: schools
Table name: teachers
Column name: gender
Schema:

CREATE TABLE `teachers` (
    `teacher_id` INT,
    `gender` VARCHAR
)

Output:
Male, Female, Other

Database name: schools
Table name: teachers
Column name: first_name
Schema:

CREATE TABLE `teachers` (
    `teacher_id` INT,
    `first_name` VARCHAR
)

Output:
0
====================
Database name: california_schools
Table name: frpm
Column name: Charter School (Y/N)
Schema:

CREATE TABLE frpm (
    CDSCode TEXT,
    Academic Year TEXT,
    County Code TEXT,
    District Code INTEGER,
    School Code TEXT,
    County Name TEXT,
    District Name TEXT,
    School Name TEXT,
    District Type TEXT,
    School Type TEXT,
    Educational Option Type TEXT,
    NSLP Provision Status TEXT,
    Charter School (Y/N) INTEGER,
    Charter School Number TEXT,
    Charter Funding Type TEXT,
    IRC INTEGER,
    Low Grade TEXT,
    High Grade TEXT,
    Enrollment (K-12) REAL,
    Free Meal Count (K-12) REAL,
    Percent (%) Eligible Free (K-12) REAL,
    FRPM Count (K-12) REAL,
    Percent (%) Eligible FRPM (K-12) REAL,
    Enrollment (Ages 5-17) REAL,
    Free Meal Count (Ages 5-17) REAL,
    Percent (%) Eligible Free (Ages 5-17) REAL,
    FRPM Count (Ages 5-17) REAL,
    Percent (%) Eligible FRPM (Ages 5-17) REAL,
    2013-14 CALPADS Fall 1 Certification Status INTEGER,
    PRIMARY KEY (CDSCode),
    FOREIGN KEY (CDSCode) REFERENCES schools (CDSCode)
);
There are 2 unique values in this column right now.
Example Values: 1, 0, None

2024-08-26 03:32:06,170 - Got LLM config
2024-08-26 03:32:06,171 - send prmopt to deepseek-coder
2024-08-26 03:32:06,173 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-26 03:32:06,371 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-26 03:32:06,759 - AI:
1, 0
2024-08-26 03:32:06,775 - Human:
As a database engineer, judge whether a specific column in database is a categorical column with given information. If it is, give all possible categories for this column.

Output format (NO EXPLANATION! NO ANY OTHER OUTPUT!):
Category1, Category2, ...

Or, this column is not categorical column:
Output format:
0
====================
E.g.
Database name: schools
Table name: teachers
Column name: gender
Schema:

CREATE TABLE `teachers` (
    `teacher_id` INT,
    `gender` VARCHAR
)

Output:
Male, Female, Other

Database name: schools
Table name: teachers
Column name: first_name
Schema:

CREATE TABLE `teachers` (
    `teacher_id` INT,
    `first_name` VARCHAR
)

Output:
0
====================
Database name: california_schools
Table name: frpm
Column name: Charter Funding Type
Schema:

CREATE TABLE frpm (
    CDSCode TEXT,
    Academic Year TEXT,
    County Code TEXT,
    District Code INTEGER,
    School Code TEXT,
    County Name TEXT,
    District Name TEXT,
    School Name TEXT,
    District Type TEXT,
    School Type TEXT,
    Educational Option Type TEXT,
    NSLP Provision Status TEXT,
    Charter School (Y/N) INTEGER,
    Charter School Number TEXT,
    Charter Funding Type TEXT,
    IRC INTEGER,
    Low Grade TEXT,
    High Grade TEXT,
    Enrollment (K-12) REAL,
    Free Meal Count (K-12) REAL,
    Percent (%) Eligible Free (K-12) REAL,
    FRPM Count (K-12) REAL,
    Percent (%) Eligible FRPM (K-12) REAL,
    Enrollment (Ages 5-17) REAL,
    Free Meal Count (Ages 5-17) REAL,
    Percent (%) Eligible Free (Ages 5-17) REAL,
    FRPM Count (Ages 5-17) REAL,
    Percent (%) Eligible FRPM (Ages 5-17) REAL,
    2013-14 CALPADS Fall 1 Certification Status INTEGER,
    PRIMARY KEY (CDSCode),

## Data Generation

In [5]:
config_data_generation = pipeline_configs['data_generation']

In [6]:
db_dict = {}
for filename in os.listdir(os.path.join(config_data_generation['input_path'], 'schema_generation')):
    if filename.endswith('.sqlite'):
        db_name = os.path.splitext(filename)[0]
        try:
            data_generation(db_name, config_data_generation)
            logging.info(f'[Data Generation]{db_name} success')
        except Exception as e:
            logging.error(f'[Data Generation]{db_name} failed: {e}')

2024-08-26 03:45:52,278 - Starting database data generation
2024-08-26 03:45:52,279 - california_schools SCHEMA loaded
2024-08-26 03:45:52,279 - california_schools REFERENCED COLS got
2024-08-26 03:45:52,280 - california_schools SCHEMA PROMPT loaded
2024-08-26 03:45:52,281 - Template found
2024-08-26 03:45:52,286 - ['schools', 'frpm', 'satscores']
2024-08-26 03:45:52,291 - Human:
As a data scientist, generate 1 row data with given schema. Make data as realistic as possible.

Schema:
CREATE TABLE schools (
    CDSCode TEXT,
    NCESDist TEXT,
    NCESSchool TEXT,
    StatusType TEXT,
    County TEXT,
    District TEXT,
    School TEXT,
    Street TEXT,
    StreetAbr TEXT,
    City TEXT,
    Zip TEXT,
    State TEXT,
    MailStreet TEXT,
    MailStrAbr TEXT,
    MailCity TEXT,
    MailZip TEXT,
    MailState TEXT,
    Phone TEXT,
    Ext TEXT,
    Website TEXT,
    OpenDate DATE,
    ClosedDate DATE,
    Charter INTEGER,
    CharterNum TEXT,
    FundingType TEXT,
    DOC TEXT,
    DOCType TEXT,
    SOC TEXT,
    SOCType TEXT,
    EdOpsCode TEXT,
    EdOpsName TEXT,
    EILCode TEXT,
    EILName TEXT,
    GSoffered TEXT,
    GSserved TEXT,
    Virtual TEXT,
    Magnet INTEGER,
    Latitude REAL,
    Longitude REAL,
    AdmFName1 TEXT,
    AdmLName1 TEXT,
    AdmEmail1 TEXT,
    AdmFName2 TEXT,
    AdmLName2 TEXT,
    AdmEmail2 TEXT,
    AdmFName3 TEXT,
    AdmLName3 TEXT,
    AdmEmail3 TEXT,
    LastUpdate DATE,
    PRIMARY KEY (CDSCode)
);

Example Row:


Here are some existed data in database, you can check their formats and values for reference.
1
CDSCode: 01100170000000
NCESDist: 0691051
NCESSchool: None
StatusType: Active
County: Alameda
District: Alameda County Office of Education
School: None
Street: 313 West Winton Avenue
StreetAbr: 313 West Winton Ave.
City: Hayward
Zip: 94544-1136
State: CA
MailStreet: 313 West Winton Avenue
MailStrAbr: 313 West Winton Ave.
MailCity: Hayward
MailZip: 94544-1136
MailState: CA
Phone: (510) 887-0152
Ext: None
Website: www.acoe.org
OpenDate: None
ClosedDate: None
Charter: None
CharterNum: None
FundingType: None
DOC: 00
DOCType: County Office of Education (COE)
SOC: None
SOCType: None
EdOpsCode: None
EdOpsName: None
EILCode: None
EILName: None
GSoffered: None
GSserved: None
Virtual: None
Magnet: None
Latitude: 37.658212
Longitude: -122.09713
AdmFName1: L Karen
AdmLName1: Monroe
AdmEmail1: lkmonroe@acoe.org
AdmFName2: None
AdmLName2: None
AdmEmail2: None
AdmFName3: None
AdmLName3: None
AdmEmail3: None
LastUpdate: 2015-06-23



Now please generate based on given values by filling blanks following(NO ANY OTHER OUTPUT):
CDSCode: 58727695838306
NCESDist:
NCESSchool:
StatusType: Closed
County:
District:
School:
Street:
StreetAbr:
City:
Zip:
State:
MailStreet:
MailStrAbr:
MailCity:
MailZip:
MailState: CA
Phone:
Ext:
Website:
OpenDate:
ClosedDate:
Charter:
CharterNum:
FundingType: Directly funded
DOC: 31
DOCType: High School District
SOC:
SOCType:
EdOpsCode: ALTERNATIVE
EdOpsName: County Community School
EILCode: None
EILName: None
GSoffered:
GSserved:
Virtual: P
Magnet:
Latitude:
Longitude:
AdmFName1:
AdmLName1:
AdmEmail1:
AdmFName2:
AdmLName2:
AdmEmail2:
AdmFName3:
AdmLName3:
AdmEmail3:
LastUpdate:


2024-08-26 03:45:52,292 - Got LLM config
2024-08-26 03:45:52,292 - send prmopt to deepseek-coder
2024-08-26 03:45:52,294 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-26 03:45:52,472 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-26 03:46:10,829 - AI:
CDSCode: 58727695838306
NCESDist: 0691051
NCESSchool: 069105101
StatusType: Closed
County: Los Angeles
District: Los Angeles Unified School District
School: Lincoln High School
Street: 3501 North Broadway
StreetAbr: 3501 N Broadway
City: Los Angeles
Zip: 90031
State: CA
MailStreet: 3501 North Broadway
MailStrAbr: 3501 N Broadway
MailCity: Los Angeles
MailZip: 90031
MailState: CA
Phone: (323) 224-4740
Ext: None
Website: www.lausd.net/lincolnhs
OpenDate: 1924-09-10
ClosedDate: 2020-06-30
Charter: 0
CharterNum: None
FundingType: Directly funded
DOC: 31
DOCType: High School District
SOC: None
SOCType: None
EdOpsCode: ALTERNATIVE
EdOpsName: County Community School
EILCode: None
EILName: None
GSoffered: 9-12
GSserved: 9-12
Virtual: P
Magnet: 0
Latitude: 34.072458
Longitude: -118.218575
AdmFName1: John
AdmLName1: Doe
AdmEmail1: jdoe@lausd.net
AdmFName2: Jane
AdmLName2: Smith
AdmEmail2: jsmith@lausd.net
AdmFName3: Robert
AdmLName3: Johnson
AdmEmail3: rjohnson@lausd.net
LastUpdate: 2020-07-01
2024-08-26 03:46:10,834 - Run data insertion SQL command:
INSERT INTO `schools` (`CDSCode`, `NCESDist`, `NCESSchool`, `StatusType`, `County`, `District`, `School`, `Street`, `StreetAbr`, `City`, `Zip`, `State`, `MailStreet`, `MailStrAbr`, `MailCity`, `MailZip`, `MailState`, `Phone`, `Ext`, `Website`, `OpenDate`, `ClosedDate`, `Charter`, `CharterNum`, `FundingType`, `DOC`, `DOCType`, `SOC`, `SOCType`, `EdOpsCode`, `EdOpsName`, `EILCode`, `EILName`, `GSoffered`, `GSserved`, `Virtual`, `Magnet`, `Latitude`, `Longitude`, `AdmFName1`, `AdmLName1`, `AdmEmail1`, `AdmFName2`, `AdmLName2`, `AdmEmail2`, `AdmFName3`, `AdmLName3`, `AdmEmail3`, `LastUpdate`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
VALUE: ['58727695838306', '0691051', '069105101', 'Closed', 'Los Angeles', 'Los Angeles Unified School District', 'Lincoln High School', '3501 North Broadway', '3501 N Broadway', 'Los Angeles', '90031', 'CA', '3501 North Broadway', '3501 N Broadway', 'Los Angeles', '90031', 'CA', '(323) 224-4740', 'None', 'www.lausd.net/lincolnhs', '1924-09-10', '2020-06-30', '0', 'None', 'Directly funded', '31', 'High School District', 'None', 'None', 'ALTERNATIVE', 'County Community School', 'None', 'None', '9-12', '9-12', 'P', '0', '34.072458', '-118.218575', 'John', 'Doe', 'jdoe@lausd.net', 'Jane', 'Smith', 'jsmith@lausd.net', 'Robert', 'Johnson', 'rjohnson@lausd.net', '2020-07-01']
2024-08-26 03:46:10,844 - Generation success.
2024-08-26 03:46:10,853 - Human:
As a data scientist, generate 1 row data with given schema. Make data as realistic as possible.

Schema:
CREATE TABLE schools (
    CDSCode TEXT,
    NCESDist TEXT,
    NCESSchool TEXT,
    StatusType TEXT,
    County TEXT,
    District TEXT,
    School TEXT,
    Street TEXT,
    StreetAbr TEXT,
    City TEXT,
    Zip TEXT,
    State TEXT,
    MailStreet TEXT,
    MailStrAbr TEXT,
    MailCity TEXT,
    MailZip TEXT,
    MailState TEXT,
    Phone TEXT,
    Ext TEXT,
    Website TEXT,
    OpenDate DATE,
    ClosedDate DATE,
    Charter INTEGER,
    CharterNum TEXT,
    FundingType TEXT,
    DOC TEXT,
    DOCType TEXT,
    SOC TEXT,
    SOCType TEXT,
    EdOpsCode TEXT,
    EdOpsName TEXT,
    EILCode TEXT,
    EILName TEXT,
    GSoffered TEXT,
    GSserved TEXT,
    Virtual TEXT,
    Magnet INTEGER,
    Latitude REAL,
    Longitude REAL,
    AdmFName1 TEXT,
    AdmLName1 TEXT,
    AdmEmail1 TEXT,
    AdmFName2 TEXT,
    AdmLName2 TEXT,
    AdmEmail2 TEXT,
    AdmFName3 TEXT,
    AdmLName3 TEXT,
    AdmEmail3 TEXT,
    LastUpdate DATE,
    PRIMARY KEY (CDSCode)
);

Example Row:


Here are some existed data in database, you can check their formats and values for reference.
1
CDSCode: 01100170000000
NCESDist: 0691051
NCESSchool: None
StatusType: Active
County: Alameda
District: Alameda County Office of Education
School: None
Street: 313 West Winton Avenue
StreetAbr: 313 West Winton Ave.
City: Hayward
Zip: 94544-1136
State: CA
MailStreet: 313 West Winton Avenue
MailStrAbr: 313 West Winton Ave.
MailCity: Hayward
MailZip: 94544-1136
MailState: CA
Phone: (510) 887-0152
Ext: None
Website: www.acoe.org
OpenDate: None
ClosedDate: None
Charter: None
CharterNum: None
FundingType: None
DOC: 00
DOCType: County Office of Education (COE)
SOC: None
SOCType: None
EdOpsCode: None
EdOpsName: None
EILCode: None
EILName: None
GSoffered: None
GSserved: None
Virtual: None
Magnet: None
Latitude: 37.658212
Longitude: -122.09713
AdmFName1: L Karen
AdmLName1: Monroe
AdmEmail1: lkmonroe@acoe.org
AdmFName2: None
AdmLName2: None
AdmEmail2: None
AdmFName3: None
AdmLName3: None
AdmEmail3: None
LastUpdate: 2015-06-23



Now please generate based on given values by filling blanks following(NO ANY OTHER OUTPUT):
CDSCode: 58727695838307
NCESDist:
NCESSchool:
StatusType: Merged
County:
District:
School:
Street:
StreetAbr:
City:
Zip:
State:
MailStreet:
MailStrAbr:
MailCity:
MailZip:
MailState: None
Phone:
Ext:
Website:
OpenDate:
ClosedDate:
Charter:
CharterNum:
FundingType: Directly funded
DOC: 42
DOCType: Unified School District
SOC:
SOCType:
EdOpsCode: VIRTUAL
EdOpsName: None
EILCode: UG
EILName: Elementary-High Combination
GSoffered:
GSserved:
Virtual: F
Magnet:
Latitude:
Longitude:
AdmFName1:
AdmLName1:
AdmEmail1:
AdmFName2:
AdmLName2:
AdmEmail2:
AdmFName3:
AdmLName3:
AdmEmail3:
LastUpdate:


2024-08-26 03:46:10,858 - Got LLM config
2024-08-26 03:46:10,860 - send prmopt to deepseek-coder
2024-08-26 03:46:10,866 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-26 03:46:11,050 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-26 03:46:29,572 - AI:
CDSCode: 58727695838307
NCESDist: 0691052
NCESSchool: 069105201
StatusType: Merged
County: Los Angeles
District: Los Angeles Unified School District
School: Lincoln High School
Street: 3501 North Broadway
StreetAbr: 3501 N Broadway
City: Los Angeles
Zip: 90031
State: CA
MailStreet: 3501 North Broadway
MailStrAbr: 3501 N Broadway
MailCity: Los Angeles
MailZip: 90031
MailState: None
Phone: (323) 224-4800
Ext: None
Website: www.lausd.net/lincolnhs
OpenDate: 1916-09-10
ClosedDate: 2020-06-30
Charter: 0
CharterNum: None
FundingType: Directly funded
DOC: 42
DOCType: Unified School District
SOC: 0691052
SOCType: Unified School District
EdOpsCode: VIRTUAL
EdOpsName: None
EILCode: UG
EILName: Elementary-High Combination
GSoffered: KG-12
GSserved: KG-12
Virtual: F
Magnet: 0
Latitude: 34.070926
Longitude: -118.218184
AdmFName1: John
AdmLName1: Doe
AdmEmail1: jdoe@lausd.net
AdmFName2: Jane
AdmLName2: Smith
AdmEmail2: jsmith@lausd.net
AdmFName3: None
AdmLName3: None
AdmEmail3: None
LastUpdate: 2021-01-15
2024-08-26 03:46:29,575 - Run data insertion SQL command:
INSERT INTO `schools` (`CDSCode`, `NCESDist`, `NCESSchool`, `StatusType`, `County`, `District`, `School`, `Street`, `StreetAbr`, `City`, `Zip`, `State`, `MailStreet`, `MailStrAbr`, `MailCity`, `MailZip`, `MailState`, `Phone`, `Ext`, `Website`, `OpenDate`, `ClosedDate`, `Charter`, `CharterNum`, `FundingType`, `DOC`, `DOCType`, `SOC`, `SOCType`, `EdOpsCode`, `EdOpsName`, `EILCode`, `EILName`, `GSoffered`, `GSserved`, `Virtual`, `Magnet`, `Latitude`, `Longitude`, `AdmFName1`, `AdmLName1`, `AdmEmail1`, `AdmFName2`, `AdmLName2`, `AdmEmail2`, `AdmFName3`, `AdmLName3`, `AdmEmail3`, `LastUpdate`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
VALUE: ['58727695838307', '0691052', '069105201', 'Merged', 'Los Angeles', 'Los Angeles Unified School District', 'Lincoln High School', '3501 North Broadway', '3501 N Broadway', 'Los Angeles', '90031', 'CA', '3501 North Broadway', '3501 N Broadway', 'Los Angeles', '90031', 'None', '(323) 224-4800', 'None', 'www.lausd.net/lincolnhs', '1916-09-10', '2020-06-30', '0', 'None', 'Directly funded', '42', 'Unified School District', '0691052', 'Unified School District', 'VIRTUAL', 'None', 'UG', 'Elementary-High Combination', 'KG-12', 'KG-12', 'F', '0', '34.070926', '-118.218184', 'John', 'Doe', 'jdoe@lausd.net', 'Jane', 'Smith', 'jsmith@lausd.net', 'None', 'None', 'None', '2021-01-15']
2024-08-26 03:46:29,600 - Generation success.
2024-08-26 03:46:29,616 - Human:
As a data scientist, generate 1 row data with given schema. Make data as realistic as possible.

Schema:
CREATE TABLE schools (
    CDSCode TEXT,
    NCESDist TEXT,
    NCESSchool TEXT,
    StatusType TEXT,
    County TEXT,
    District TEXT,
    School TEXT,
    Street TEXT,
    StreetAbr TEXT,
    City TEXT,
    Zip TEXT,
    State TEXT,
    MailStreet TEXT,
    MailStrAbr TEXT,
    MailCity TEXT,
    MailZip TEXT,
    MailState TEXT,
    Phone TEXT,
    Ext TEXT,
    Website TEXT,
    OpenDate DATE,
    ClosedDate DATE,
    Charter INTEGER,
    CharterNum TEXT,
    FundingType TEXT,
    DOC TEXT,
    DOCType TEXT,
    SOC TEXT,
    SOCType TEXT,
    EdOpsCode TEXT,
    EdOpsName TEXT,
    EILCode TEXT,
    EILName TEXT,
    GSoffered TEXT,
    GSserved TEXT,
    Virtual TEXT,
    Magnet INTEGER,
    Latitude REAL,
    Longitude REAL,
    AdmFName1 TEXT,
    AdmLName1 TEXT,
    AdmEmail1 TEXT,
    AdmFName2 TEXT,
    AdmLName2 TEXT,
    AdmEmail2 TEXT,
    AdmFName3 TEXT,
    AdmLName3 TEXT,
    AdmEmail3 TEXT,
    LastUpdate DATE,
    PRIMARY KEY (CDSCode)
);

Example Row:


Here are some existed data in database, you can check their formats and values for reference.
1
CDSCode: 01100170000000
NCESDist: 0691051
NCESSchool: None
StatusType: Active
County: Alameda
District: Alameda County Office of Education
School: None
Street: 313 West Winton Avenue
StreetAbr: 313 West Winton Ave.
City: Hayward
Zip: 94544-1136
State: CA
MailStreet: 313 West Winton Avenue
MailStrAbr: 313 West Winton Ave.
MailCity: Hayward
MailZip: 94544-1136
MailState: CA
Phone: (510) 887-0152
Ext: None
Website: www.acoe.org
OpenDate: None
ClosedDate: None
Charter: None
CharterNum: None
FundingType: None
DOC: 00
DOCType: County Office of Education (COE)
SOC: None
SOCType: None
EdOpsCode: None
EdOpsName: None
EILCode: None
EILName: None
GSoffered: None
GSserved: None
Virtual: None
Magnet: None
Latitude: 37.658212
Longitude: -122.09713
AdmFName1: L Karen
AdmLName1: Monroe
AdmEmail1: lkmonroe@acoe.org
AdmFName2: None
AdmLName2: None
AdmEmail2: None
AdmFName3: None
AdmLName3: None
AdmEmail3: None
LastUpdate: 2015-06-23



Now please generate based on given values by filling blanks following(NO ANY OTHER OUTPUT):
CDSCode: 58727695838308
NCESDist:
NCESSchool:
StatusType: Closed
County:
District:
School:
Street:
StreetAbr:
City:
Zip:
State:
MailStreet:
MailStrAbr:
MailCity:
MailZip:
MailState: CA
Phone:
Ext:
Website:
OpenDate:
ClosedDate:
Charter:
CharterNum:
FundingType: Directly funded
DOC: 42
DOCType: County Community Schools
SOC:
SOCType:
EdOpsCode: OPP
EdOpsName: Opportunity School
EILCode: K8
EILName: Ungraded
GSoffered:
GSserved:
Virtual: N
Magnet:
Latitude:
Longitude:
AdmFName1:
AdmLName1:
AdmEmail1:
AdmFName2:
AdmLName2:
AdmEmail2:
AdmFName3:
AdmLName3:
AdmEmail3:
LastUpdate:


2024-08-26 03:46:29,641 - Got LLM config
2024-08-26 03:46:29,643 - send prmopt to deepseek-coder
2024-08-26 03:46:29,648 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-26 03:46:29,851 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-26 03:46:47,260 - AI:
CDSCode: 58727695838308
NCESDist: 0691052
NCESSchool: 069105201
StatusType: Closed
County: Los Angeles
District: Los Angeles Unified School District
School: Opportunity School
Street: 1234 Main Street
StreetAbr: 1234 Main St.
City: Los Angeles
Zip: 90012
State: CA
MailStreet: 1234 Main Street
MailStrAbr: 1234 Main St.
MailCity: Los Angeles
MailZip: 90012
MailState: CA
Phone: (213) 555-1234
Ext: 101
Website: www.opportunityschool.org
OpenDate: 2005-09-01
ClosedDate: 2020-06-30
Charter: 0
CharterNum: None
FundingType: Directly funded
DOC: 42
DOCType: County Community Schools
SOC: None
SOCType: None
EdOpsCode: OPP
EdOpsName: Opportunity School
EILCode: K8
EILName: Ungraded
GSoffered: None
GSserved: None
Virtual: N
Magnet: 0
Latitude: 34.052235
Longitude: -118.243683
AdmFName1: John
AdmLName1: Doe
AdmEmail1: jdoe@opportunityschool.org
AdmFName2: Jane
AdmLName2: Smith
AdmEmail2: jsmith@opportunityschool.org
AdmFName3: Robert
AdmLName3: Johnson
AdmEmail3: rjohnson@opportunityschool.org
LastUpdate: 2020-07-01
2024-08-26 03:46:47,264 - Run data insertion SQL command:
INSERT INTO `schools` (`CDSCode`, `NCESDist`, `NCESSchool`, `StatusType`, `County`, `District`, `School`, `Street`, `StreetAbr`, `City`, `Zip`, `State`, `MailStreet`, `MailStrAbr`, `MailCity`, `MailZip`, `MailState`, `Phone`, `Ext`, `Website`, `OpenDate`, `ClosedDate`, `Charter`, `CharterNum`, `FundingType`, `DOC`, `DOCType`, `SOC`, `SOCType`, `EdOpsCode`, `EdOpsName`, `EILCode`, `EILName`, `GSoffered`, `GSserved`, `Virtual`, `Magnet`, `Latitude`, `Longitude`, `AdmFName1`, `AdmLName1`, `AdmEmail1`, `AdmFName2`, `AdmLName2`, `AdmEmail2`, `AdmFName3`, `AdmLName3`, `AdmEmail3`, `LastUpdate`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
VALUE: ['58727695838308', '0691052', '069105201', 'Closed', 'Los Angeles', 'Los Angeles Unified School District', 'Opportunity School', '1234 Main Street', '1234 Main St.', 'Los Angeles', '90012', 'CA', '1234 Main Street', '1234 Main St.', 'Los Angeles', '90012', 'CA', '(213) 555-1234', '101', 'www.opportunityschool.org', '2005-09-01', '2020-06-30', '0', 'None', 'Directly funded', '42', 'County Community Schools', 'None', 'None', 'OPP', 'Opportunity School', 'K8', 'Ungraded', 'None', 'None', 'N', '0', '34.052235', '-118.243683', 'John', 'Doe', 'jdoe@opportunityschool.org', 'Jane', 'Smith', 'jsmith@opportunityschool.org', 'Robert', 'Johnson', 'rjohnson@opportunityschool.org', '2020-07-01']
2024-08-26 03:46:47,292 - Generation success.
2024-08-26 03:46:47,364 - Human:
As a data scientist, generate 1 row data with given schema. Make data as realistic as possible.

Schema:
CREATE TABLE frpm (
    CDSCode TEXT,
    Academic Year TEXT,
    County Code TEXT,
    District Code INTEGER,
    School Code TEXT,
    County Name TEXT,
    District Name TEXT,
    School Name TEXT,
    District Type TEXT,
    School Type TEXT,
    Educational Option Type TEXT,
    NSLP Provision Status TEXT,
    Charter School (Y/N) INTEGER,
    Charter School Number TEXT,
    Charter Funding Type TEXT,
    IRC INTEGER,
    Low Grade TEXT,
    High Grade TEXT,
    Enrollment (K-12) REAL,
    Free Meal Count (K-12) REAL,
    Percent (%) Eligible Free (K-12) REAL,
    FRPM Count (K-12) REAL,
    Percent (%) Eligible FRPM (K-12) REAL,
    Enrollment (Ages 5-17) REAL,
    Free Meal Count (Ages 5-17) REAL,
    Percent (%) Eligible Free (Ages 5-17) REAL,
    FRPM Count (Ages 5-17) REAL,
    Percent (%) Eligible FRPM (Ages 5-17) REAL,
    2013-14 CALPADS Fall 1 Certification Status INTEGER,
    PRIMARY KEY (CDSCode),
    FOREIGN KEY (CDSCode) REFERENCES schools (CDSCode)
);

Example Row:


Here are some existed data in database, you can check their formats and values for reference.
1
CDSCode: 01100170109835
Academic Year: 2014-2015
County Code: 01
District Code: 10017
School Code: 0109835
County Name: Alameda
District Name: Alameda County Office of Education
School Name: FAME Public Charter
District Type: County Office of Education (COE)
School Type: K-12 Schools (Public)
Educational Option Type: Traditional
NSLP Provision Status: None
Charter School (Y/N): 1
Charter School Number: 0728
Charter Funding Type: Directly funded
IRC: 1
Low Grade: K
High Grade: 12
Enrollment (K-12): 1087.0
Free Meal Count (K-12): 565.0
Percent (%) Eligible Free (K-12): 0.519779208831647
FRPM Count (K-12): 715.0
Percent (%) Eligible FRPM (K-12): 0.657773689052438
Enrollment (Ages 5-17): 1070.0
Free Meal Count (Ages 5-17): 553.0
Percent (%) Eligible Free (Ages 5-17): 0.516822429906542
FRPM Count (Ages 5-17): 702.0
Percent (%) Eligible FRPM (Ages 5-17): 0.65607476635514
2013-14 CALPADS Fall 1 Certification Status: 1



Now please generate based on given values by filling blanks following(NO ANY OTHER OUTPUT):
CDSCode: 58727695838306
Academic Year:
County Code:
District Code:
School Code:
County Name:
District Name:
School Name:
District Type: Junior High School District
School Type: County Community
Educational Option Type: Alternative Education School
NSLP Provision Status: Provision 2
Charter School (Y/N): 1

In [ ]:
db_name = 'california_schools'
data_generation(db_name, config_data_generation)

## Template Generation

In [6]:
config_temp_generation = pipeline_configs['temp_generation']

In [ ]:
db_dict = {}
for filename in os.listdir(os.path.join(config_temp_generation['input_path'], 'schema_generation')):
    if filename.endswith('.sqlite'):
        db_name = os.path.splitext(filename)[0]
        try:
            temp_generation(db_name, config_temp_generation)
        except Exception as e:
            logging.error(f'[Temp Generation]{db_name} failed: {e}')

In [7]:
db_name = 'UHC'
temp_generation(db_name, config_temp_generation)

2024-08-19 06:11:14,343 - Starting template generation
2024-08-19 06:11:14,344 - UHC SCHEMA loaded
2024-08-19 06:11:14,346 - UHC SCHEMA PROMPT loaded
2024-08-19 06:11:14,347 - Template found
2024-08-19 06:11:14,349 - No evidence found. Try generation without evidence.
2024-08-19 06:11:14,350 - Human:
As a professor teaching database courses, generate 20 question templates with corresponding SQL answer templates for examination.

Requirements of question templates:

1, As realistic as possible

2, Evidence must be used when students answer the questions. In the other words, questions should be unsolvable without evidence information.

3, Use `` around table / column names to prevent reserved word conflicts

4, (Optional) You can use `{TABLE}` to indicate any tables, `{COLUMN}` to indicate any columns.
For example, you can have 'find all entries of {COLUMN} from table {TABLE}.' in question and 'SELECT `{COLUMN}` FROM `{TABLE}`' in SQL answer.
If you want to use this, ensure that any table / column can be placed in the designated location and does not affect the plausibility of the question

5, (Optional) You can use {table_name.column_name} to indicate an arbitrary value in this column.
For example, suggest there is a column student_id in table student.
When you want to have 'student with id A0001' in question, use 'student with id {student.student_id}'
When you want to have 'WHERE `student`.`student_id` == A0001' in SQL answer, use 'WHERE `student`.`student_id` == {student.student_id}'


Schema of database used:
CREATE TABLE patients (
    patient_id INT,
    first_name VARCHAR,
    last_name VARCHAR,
    date_of_birth DATE,
    age INT,
    gender VARCHAR,
    address VARCHAR,
    phone_number VARCHAR,
    email VARCHAR,
    medical_history TEXT,
    PRIMARY KEY (patient_id)
);
CREATE TABLE doctors (
    doctor_id INT,
    first_name VARCHAR,
    last_name VARCHAR,
    specialization VARCHAR,
    phone_number VARCHAR,
    email VARCHAR,
    biography TEXT,
    PRIMARY KEY (doctor_id)
);
CREATE TABLE appointments (
    appointment_id INT,
    patient_id INT,
    doctor_id INT,
    appointment_date DATETIME,
    reason TEXT,
    status VARCHAR,
    PRIMARY KEY (appointment_id),
    FOREIGN KEY (doctor_id) REFERENCES doctors (doctor_id),
    FOREIGN KEY (patient_id) REFERENCES patients (patient_id)
);
CREATE TABLE medical_records (
    record_id INT,
    patient_id INT,
    doctor_id INT,
    record_date DATETIME,
    diagnosis TEXT,
    treatment TEXT,
    notes TEXT,
    PRIMARY KEY (record_id),
    FOREIGN KEY (doctor_id) REFERENCES doctors (doctor_id),
    FOREIGN KEY (patient_id) REFERENCES patients (patient_id)
);
CREATE TABLE prescriptions (
    prescription_id INT,
    patient_id INT,
    doctor_id INT,
    prescription_date DATETIME,
    medication TEXT,
    dosage TEXT,
    instructions TEXT,
    PRIMARY KEY (prescription_id),
    FOREIGN KEY (doctor_id) REFERENCES doctors (doctor_id),
    FOREIGN KEY (patient_id) REFERENCES patients (patient_id)
);
CREATE TABLE billing (
    billing_id INT,
    patient_id INT,
    amount FLOAT,
    billing_date DATE,
    status VARCHAR,
    description TEXT,
    PRIMARY KEY (billing_id),
    FOREIGN KEY (patient_id) REFERENCES patients (patient_id)
);
CREATE TABLE insurance (
    insurance_id INT,
    patient_id INT,
    provider VARCHAR,
    policy_number VARCHAR,
    effective_date DATE,
    expiration_date DATE,
    coverage_details TEXT,
    PRIMARY KEY (insurance_id),
    FOREIGN KEY (patient_id) REFERENCES patients (patient_id)
);
CREATE TABLE staff (
    staff_id INT,
    first_name VARCHAR,
    last_name VARCHAR,
    role VARCHAR,
    phone_number VARCHAR,
    email VARCHAR,
    responsibilities TEXT,
    PRIMARY KEY (staff_id)
);

You should generate evidence on your own.


Output format (NO ANY OTHER OUTPUT):
1
Q: {Question template}
E: {Evidence}
A:
```sql
{SQL answer template(executable)}
```

2
Q: {Question template}
E: {Evidence}
A:
```sql
{SQL answer template(executable)}
```
...

2024-08-19 06:11:14,351 - Got LLM config
2024-08-19 06:11:14,351 - send prmopt to deepseek-coder
2024-08-19 06:11:14,353 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:11:14,566 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:12:26,431 - AI:
1
Q: Find the full name and phone number of the patient with ID {patients.patient_id}.
E: The patient's ID is provided as evidence.
A:
```sql
SELECT `first_name`, `last_name`, `phone_number`
FROM `patients`
WHERE `patient_id` = {patients.patient_id};
```

2
Q: List all appointments scheduled for the doctor with ID {doctors.doctor_id} on {appointments.appointment_date}.
E: The doctor's ID and the appointment date are provided as evidence.
A:
```sql
SELECT *
FROM `appointments`
WHERE `doctor_id` = {doctors.doctor_id}
AND `appointment_date` = '{appointments.appointment_date}';
```

3
Q: Retrieve the diagnosis and treatment for the medical record with ID {medical_records.record_id}.
E: The medical record ID is provided as evidence.
A:
```sql
SELECT `diagnosis`, `treatment`
FROM `medical_records`
WHERE `record_id` = {medical_records.record_id};
```

4
Q: Find the total amount billed for the patient with ID {patients.patient_id}.
E: The patient's ID is provided as evidence.
A:
```sql
SELECT SUM(`amount`) AS total_amount
FROM `billing`
WHERE `patient_id` = {patients.patient_id};
```

5
Q: List all medications prescribed to the patient with ID {patients.patient_id}.
E: The patient's ID is provided as evidence.
A:
```sql
SELECT `medication`
FROM `prescriptions`
WHERE `patient_id` = {patients.patient_id};
```

6
Q: Retrieve the full name and specialization of the doctor with ID {doctors.doctor_id}.
E: The doctor's ID is provided as evidence.
A:
```sql
SELECT `first_name`, `last_name`, `specialization`
FROM `doctors`
WHERE `doctor_id` = {doctors.doctor_id};
```

7
Q: Find the insurance provider and policy number for the patient with ID {patients.patient_id}.
E: The patient's ID is provided as evidence.
A:
```sql
SELECT `provider`, `policy_number`
FROM `insurance`
WHERE `patient_id` = {patients.patient_id};
```

8
Q: List all staff members with the role of {staff.role}.
E: The staff role is provided as evidence.
A:
```sql
SELECT `first_name`, `last_name`
FROM `staff`
WHERE `role` = '{staff.role}';
```

9
Q: Retrieve the appointment date and status for the appointment with ID {appointments.appointment_id}.
E: The appointment ID is provided as evidence.
A:
```sql
SELECT `appointment_date`, `status`
FROM `appointments`
WHERE `appointment_id` = {appointments.appointment_id};
```

10
Q: Find the total number of patients born after {patients.date_of_birth}.
E: The date of birth is provided as evidence.
A:
```sql
SELECT COUNT(*) AS total_patients
FROM `patients`
WHERE `date_of_birth` > '{patients.date_of_birth}';
```

11
Q: List all appointments that were scheduled for the patient with ID {patients.patient_id} in the year {appointments.appointment_date}.
E: The patient's ID and the year are provided as evidence.
A:
```sql
SELECT *
FROM `appointments`
WHERE `patient_id` = {patients.patient_id}
AND YEAR(`appointment_date`) = {appointments.appointment_date};
```

12
Q: Retrieve the full name and email of the staff member with ID {staff.staff_id}.
E: The staff member's ID is provided as evidence.
A:
```sql
SELECT `first_name`, `last_name`, `email`
FROM `staff`
WHERE `staff_id` = {staff.staff_id};
```

13
Q: Find the total number of doctors specialized in {doctors.specialization}.
E: The specialization is provided as evidence.
A:
```sql
SELECT COUNT(*) AS total_doctors
FROM `doctors`
WHERE `specialization` = '{doctors.specialization}';
```

14
Q: List all medical records created by the doctor with ID {doctors.doctor_id}.
E: The doctor's ID is provided as evidence.
A:
```sql
SELECT *
FROM `medical_records`
WHERE `doctor_id` = {doctors.doctor_id};
```

15
Q: Retrieve the full name and address of the patient who has the billing record with ID {billing.billing_id}.
E: The billing record ID is provided as evidence.
A:
```sql
SELECT `first_name`, `last_name`, `address`
FROM `patients`
JOIN `billing` ON `patients`.`patient_id` = `billing`.`patient_id`
WHERE `billing`.`billing_id` = {billing.billing_id};
```

16
Q: Find the total number of appointments that were canceled.
E: The status of appointments is provided as evidence.
A:
```sql
SELECT COUNT(*) AS total_canceled_appointments
FROM `appointments`
WHERE `status` = 'Canceled';
```

17
Q: List all prescriptions issued by the doctor with ID {doctors.doctor_id}.
E: The doctor's ID is provided as evidence.
A:
```sql
SELECT *
FROM `prescriptions`
WHERE `doctor_id` = {doctors.doctor_id};
```

18
Q: Retrieve the full name and phone number of the patient who has the insurance record with ID {insurance.insurance_id}.
E: The insurance record ID is provided as evidence.
A:
```sql
SELECT `first_name`, `last_name`, `phone_number`
FROM `patients`
JOIN `insurance` ON `patients`.`patient_id` = `insurance`.`patient_id`
WHERE `insurance`.`insurance_id` = {insurance.insurance_id};
```

19
Q: Find the total number of medical records for the patient with ID {patients.patient_id}.
E: The patient's ID is provided as evidence.
A:
```sql
SELECT COUNT(*) AS total_medical_records
FROM `medical_records`
WHERE `patient_id` = {patients.patient_id};
```

20
Q: List all appointments that were scheduled for the doctor with ID {doctors.doctor_id} in the month of {appointments.appointment_date}.
E: The doctor's ID and the month are provided as evidence.
A:
```sql
SELECT *
FROM `appointments`
WHERE `doctor_id` = {doctors.doctor_id}
AND MONTH(`appointment_date`) = {appointments.appointment_date};
```
2024-08-19 06:12:26,436 - Generate 20 templates.

## Question Generation

In [8]:
config_ques_generation = pipeline_configs['ques_generation']

In [9]:
db_dict = {}
for filename in os.listdir(os.path.join(config_ques_generation['input_path'], 'schema_generation')):
    if filename.endswith('.sqlite'):
        db_name = os.path.splitext(filename)[0]
        try:
            ques_generation(db_name, config_ques_generation)
        except Exception as e:
            logging.error(f'[Ques Generation]{db_name} failed: {e}')

2024-08-19 06:12:33,914 - Starting question generation
2024-08-19 06:12:33,920 - california_schools SCHEMA loaded
2024-08-19 06:12:33,937 - california_schools SCHEMA PROMPT loaded
2024-08-19 06:12:33,943 - Find question templates in generated_templates.json
2024-08-19 06:12:33,943 - Find 15 question templates
2024-08-19 06:12:34,314 - 1 executable with result.
2024-08-19 06:12:34,319 - 1 executable with result.
2024-08-19 06:12:34,541 - 3 executable with result.
2024-08-19 06:12:34,628 - 3 executable with result.
2024-08-19 06:12:34,635 - 3 executable with result.
2024-08-19 06:12:34,785 - Generate 11 new questions totally.
2024-08-19 06:12:34,786 - Starting question generation
2024-08-19 06:12:34,787 - UHC SCHEMA loaded
2024-08-19 06:12:34,788 - UHC SCHEMA PROMPT loaded
2024-08-19 06:12:34,800 - Find question templates in generated_templates.json
2024-08-19 06:12:34,800 - Find 20 question templates
2024-08-19 06:12:34,802 - 3 executable with result.
2024-08-19 06:12:34,825 - 1 executable with result.
2024-08-19 06:12:34,828 - 3 executable with result.
2024-08-19 06:12:34,831 - 3 executable with result.
2024-08-19 06:12:34,834 - 3 executable with result.
2024-08-19 06:12:34,836 - 3 executable with result.
2024-08-19 06:12:34,841 - 3 executable with result.
2024-08-19 06:12:34,843 - 3 executable with result.
2024-08-19 06:12:34,846 - 3 executable with result.
2024-08-19 06:12:34,848 - 3 executable with result.
2024-08-19 06:12:34,874 - 3 executable with result.
2024-08-19 06:12:34,877 - 3 executable with result.
2024-08-19 06:12:34,879 - 3 executable with result.
2024-08-19 06:12:34,881 - 3 executable with result.
2024-08-19 06:12:34,885 - 3 executable with result.
2024-08-19 06:12:34,888 - 3 executable with result.
2024-08-19 06:12:34,893 - 3 executable with result.
2024-08-19 06:12:34,918 - Generate 49 new questions totally.

In [8]:
db_name = 'california_schools'
ques_generation(db_name, config_ques_generation)

2024-08-19 00:30:15,422 - Starting question generation
2024-08-19 00:30:15,423 - california_schools SCHEMA loaded
2024-08-19 00:30:15,424 - california_schools SCHEMA PROMPT loaded
2024-08-19 00:30:15,425 - Template found
2024-08-19 00:30:15,426 - Find question templates in generated_templates.json
2024-08-19 00:30:15,426 - Find 15 question templates
2024-08-19 00:30:15,860 - 1 executable with result.
2024-08-19 00:30:15,860 - 1 executable with result.
2024-08-19 00:30:16,579 - 1 executable with result.
2024-08-19 00:30:16,707 - 3 executable with result.
2024-08-19 00:30:16,721 - 3 executable with result.
2024-08-19 00:30:16,856 - Generate 9 new questions totally.

## Question revision

In [11]:
config_ques_revision = pipeline_configs['ques_revision']

In [ ]:
db_dict = {}
for filename in os.listdir(os.path.join(config_ques_revision['input_path'], 'ques_revision')):
    if filename.endswith('.sqlite'):
        db_name = os.path.splitext(filename)[0]
        try:
            ques_revision(db_name, config_ques_revision)
        except Exception as e:
            logging.error(f'[Ques revision]{db_name} failed: {e}')

In [12]:
db_name = 'UHC'
ques_revision(db_name, config_ques_revision)

2024-08-19 06:12:58,302 - Template found
2024-08-19 06:12:58,304 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Find the full name and phone number of the patient with ID {patients.patient_id}.
Evidence: The patient's ID is provided as evidence.
SQL answer: SELECT `first_name`, `last_name`, `phone_number`
FROM `patients`
WHERE `patient_id` = 29;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:12:58,306 - Got LLM config
2024-08-19 06:12:58,306 - send prmopt to deepseek-coder
2024-08-19 06:12:58,308 - Starting new HTTPS connection (1): api.deepseek.com:443

2024-08-19 06:12:58,582 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:12:59,551 - AI:
Retrieve the full name and phone number of the patient whose ID is 29.
2024-08-19 06:12:59,554 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Find the full name and phone number of the patient with ID {patients.patient_id}.
Evidence: The patient's ID is provided as evidence.
SQL answer: SELECT `first_name`, `last_name`, `phone_number`
FROM `patients`
WHERE `patient_id` = 3;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:12:59,556 - Got LLM config
2024-08-19 06:12:59,556 - send prmopt to deepseek-coder
2024-08-19 06:12:59,558 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:12:59,943 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:00,902 - AI:
Retrieve the full name and phone number of the patient whose ID is 3.
2024-08-19 06:13:00,904 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Find the full name and phone number of the patient with ID {patients.patient_id}.
Evidence: The patient's ID is provided as evidence.
SQL answer: SELECT `first_name`, `last_name`, `phone_number`
FROM `patients`
WHERE `patient_id` = 26;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:00,907 - Got LLM config
2024-08-19 06:13:00,907 - send prmopt to deepseek-coder
2024-08-19 06:13:00,909 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:01,124 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:02,133 - AI:
Provide the full name and phone number of the patient with ID 26.
2024-08-19 06:13:02,136 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: List all appointments scheduled for the doctor with ID {doctors.doctor_id} on {appointments.appointment_date}.
Evidence: The doctor's ID and the appointment date are provided as evidence.
SQL answer: SELECT *
FROM `appointments`
WHERE `doctor_id` = 8
AND `appointment_date` = '"2023-04-17 10:00:00"';

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:02,138 - Got LLM config
2024-08-19 06:13:02,138 - send prmopt to deepseek-coder
2024-08-19 06:13:02,140 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:02,337 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:03,866 - AI:
List all appointments scheduled for Doctor ID 8 on April 17, 2023, at 10:00 AM.
2024-08-19 06:13:03,870 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Retrieve the diagnosis and treatment for the medical record with ID {medical_records.record_id}.
Evidence: The medical record ID is provided as evidence.
SQL answer: SELECT `diagnosis`, `treatment`
FROM `medical_records`
WHERE `record_id` = 10;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:03,872 - Got LLM config
2024-08-19 06:13:03,872 - send prmopt to deepseek-coder
2024-08-19 06:13:03,874 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:04,103 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:05,146 - AI:
Provide the diagnosis and treatment details for the medical record with ID 10.
2024-08-19 06:13:05,147 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Retrieve the diagnosis and treatment for the medical record with ID {medical_records.record_id}.
Evidence: The medical record ID is provided as evidence.
SQL answer: SELECT `diagnosis`, `treatment`
FROM `medical_records`
WHERE `record_id` = 6;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:05,148 - Got LLM config
2024-08-19 06:13:05,148 - send prmopt to deepseek-coder
2024-08-19 06:13:05,149 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:05,355 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:06,356 - AI:
Retrieve the diagnosis and treatment for the medical record with ID 6.
2024-08-19 06:13:06,358 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Retrieve the diagnosis and treatment for the medical record with ID {medical_records.record_id}.
Evidence: The medical record ID is provided as evidence.
SQL answer: SELECT `diagnosis`, `treatment`
FROM `medical_records`
WHERE `record_id` = 9;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:06,359 - Got LLM config
2024-08-19 06:13:06,360 - send prmopt to deepseek-coder
2024-08-19 06:13:06,362 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:06,797 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:07,689 - AI:
Get the diagnosis and treatment details for the medical record identified by ID 9.
2024-08-19 06:13:07,690 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Find the total amount billed for the patient with ID {patients.patient_id}.
Evidence: The patient's ID is provided as evidence.
SQL answer: SELECT SUM(`amount`) AS total_amount
FROM `billing`
WHERE `patient_id` = 1;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:07,690 - Got LLM config
2024-08-19 06:13:07,691 - send prmopt to deepseek-coder
2024-08-19 06:13:07,692 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:07,881 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:08,733 - AI:
Calculate the total billed amount for the patient with ID 1.
2024-08-19 06:13:08,735 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Find the total amount billed for the patient with ID {patients.patient_id}.
Evidence: The patient's ID is provided as evidence.
SQL answer: SELECT SUM(`amount`) AS total_amount
FROM `billing`
WHERE `patient_id` = 8;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:08,737 - Got LLM config
2024-08-19 06:13:08,738 - send prmopt to deepseek-coder
2024-08-19 06:13:08,740 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:08,953 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:09,841 - AI:
Calculate the total billed amount for the patient with ID 8.
2024-08-19 06:13:09,843 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Find the total amount billed for the patient with ID {patients.patient_id}.
Evidence: The patient's ID is provided as evidence.
SQL answer: SELECT SUM(`amount`) AS total_amount
FROM `billing`
WHERE `patient_id` = 2;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:09,844 - Got LLM config
2024-08-19 06:13:09,844 - send prmopt to deepseek-coder
2024-08-19 06:13:09,846 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:10,049 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:10,919 - AI:
What is the total amount billed for the patient with ID 2?
2024-08-19 06:13:10,921 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: List all medications prescribed to the patient with ID {patients.patient_id}.
Evidence: The patient's ID is provided as evidence.
SQL answer: SELECT `medication`
FROM `prescriptions`
WHERE `patient_id` = 29;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:10,922 - Got LLM config
2024-08-19 06:13:10,922 - send prmopt to deepseek-coder
2024-08-19 06:13:10,923 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:11,195 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:12,166 - AI:
List the medications prescribed to the patient with ID 29.
2024-08-19 06:13:12,168 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: List all medications prescribed to the patient with ID {patients.patient_id}.
Evidence: The patient's ID is provided as evidence.
SQL answer: SELECT `medication`
FROM `prescriptions`
WHERE `patient_id` = 26;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:12,169 - Got LLM config
2024-08-19 06:13:12,169 - send prmopt to deepseek-coder
2024-08-19 06:13:12,170 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:12,405 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:13,171 - AI:
List the medications prescribed to the patient with ID 26.
2024-08-19 06:13:13,175 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: List all medications prescribed to the patient with ID {patients.patient_id}.
Evidence: The patient's ID is provided as evidence.
SQL answer: SELECT `medication`
FROM `prescriptions`
WHERE `patient_id` = 6;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:13,176 - Got LLM config
2024-08-19 06:13:13,176 - send prmopt to deepseek-coder
2024-08-19 06:13:13,178 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:13,396 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:14,217 - AI:
List the medications prescribed to the patient with ID 6.
2024-08-19 06:13:14,219 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Retrieve the full name and specialization of the doctor with ID {doctors.doctor_id}.
Evidence: The doctor's ID is provided as evidence.
SQL answer: SELECT `first_name`, `last_name`, `specialization`
FROM `doctors`
WHERE `doctor_id` = 6;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:14,221 - Got LLM config
2024-08-19 06:13:14,222 - send prmopt to deepseek-coder
2024-08-19 06:13:14,224 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:14,471 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:15,424 - AI:
Get the full name and specialization of the doctor whose ID is 6.
2024-08-19 06:13:15,427 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Retrieve the full name and specialization of the doctor with ID {doctors.doctor_id}.
Evidence: The doctor's ID is provided as evidence.
SQL answer: SELECT `first_name`, `last_name`, `specialization`
FROM `doctors`
WHERE `doctor_id` = 10;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:15,430 - Got LLM config
2024-08-19 06:13:15,431 - send prmopt to deepseek-coder
2024-08-19 06:13:15,433 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:15,682 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:16,662 - AI:
Retrieve the full name and specialization of the doctor with ID 10.
2024-08-19 06:13:16,663 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Retrieve the full name and specialization of the doctor with ID {doctors.doctor_id}.
Evidence: The doctor's ID is provided as evidence.
SQL answer: SELECT `first_name`, `last_name`, `specialization`
FROM `doctors`
WHERE `doctor_id` = 8;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:16,664 - Got LLM config
2024-08-19 06:13:16,665 - send prmopt to deepseek-coder
2024-08-19 06:13:16,666 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:16,901 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:17,834 - AI:
Retrieve the full name and specialization of the doctor with ID 8.
2024-08-19 06:13:17,836 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Find the insurance provider and policy number for the patient with ID {patients.patient_id}.
Evidence: The patient's ID is provided as evidence.
SQL answer: SELECT `provider`, `policy_number`
FROM `insurance`
WHERE `patient_id` = 23;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:17,837 - Got LLM config
2024-08-19 06:13:17,837 - send prmopt to deepseek-coder
2024-08-19 06:13:17,838 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:18,087 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:19,044 - AI:
Find the insurance provider and policy number for the patient with ID 23.
2024-08-19 06:13:19,047 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Find the insurance provider and policy number for the patient with ID {patients.patient_id}.
Evidence: The patient's ID is provided as evidence.
SQL answer: SELECT `provider`, `policy_number`
FROM `insurance`
WHERE `patient_id` = 26;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:19,049 - Got LLM config
2024-08-19 06:13:19,050 - send prmopt to deepseek-coder
2024-08-19 06:13:19,053 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:19,286 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:20,387 - AI:
Find the insurance provider and policy number for the patient with ID 26.
2024-08-19 06:13:20,390 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Find the insurance provider and policy number for the patient with ID {patients.patient_id}.
Evidence: The patient's ID is provided as evidence.
SQL answer: SELECT `provider`, `policy_number`
FROM `insurance`
WHERE `patient_id` = 25;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:20,394 - Got LLM config
2024-08-19 06:13:20,394 - send prmopt to deepseek-coder
2024-08-19 06:13:20,396 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:20,580 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:21,621 - AI:
Find the insurance provider and policy number for the patient with ID 25.
2024-08-19 06:13:21,622 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: List all staff members with the role of {staff.role}.
Evidence: The staff role is provided as evidence.
SQL answer: SELECT `first_name`, `last_name`
FROM `staff`
WHERE `role` = '"Physical Therapist"';

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:21,624 - Got LLM config
2024-08-19 06:13:21,624 - send prmopt to deepseek-coder
2024-08-19 06:13:21,624 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:21,824 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:22,614 - AI:
List all physical therapists along with their first and last names.
2024-08-19 06:13:22,618 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: List all staff members with the role of {staff.role}.
Evidence: The staff role is provided as evidence.
SQL answer: SELECT `first_name`, `last_name`
FROM `staff`
WHERE `role` = '"Radiologist"';

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:22,621 - Got LLM config
2024-08-19 06:13:22,622 - send prmopt to deepseek-coder
2024-08-19 06:13:22,623 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:22,844 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:23,598 - AI:
List all radiologists in the staff directory.
2024-08-19 06:13:23,601 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: List all staff members with the role of {staff.role}.
Evidence: The staff role is provided as evidence.
SQL answer: SELECT `first_name`, `last_name`
FROM `staff`
WHERE `role` = 'Pharmacist';

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:23,604 - Got LLM config
2024-08-19 06:13:23,604 - send prmopt to deepseek-coder
2024-08-19 06:13:23,606 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:23,891 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:24,686 - AI:
List all pharmacists in the staff directory.
2024-08-19 06:13:24,688 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Retrieve the appointment date and status for the appointment with ID {appointments.appointment_id}.
Evidence: The appointment ID is provided as evidence.
SQL answer: SELECT `appointment_date`, `status`
FROM `appointments`
WHERE `appointment_id` = 106;

Return rewroted question directly. NO ANY OTHER OUTPUT

2024-08-19 06:13:24,689 - Got LLM config
2024-08-19 06:13:24,690 - send prmopt to deepseek-coder
2024-08-19 06:13:24,692 - Starting new HTTPS connection (1): api.deepseek.com:443
2024-08-19 06:13:24,906 - https://api.deepseek.com:443 "POST /chat/completions HTTP/11" 200 None
2024-08-19 06:13:25,806 - AI:
Provide the appointment date and status for the appointment with ID 106.
2024-08-19 06:13:25,809 - Human:
Given a question-SQL pair, you should:
1, Fill placeholders in the question to correctly describe what the SQL answer does.
2, Rewrite the question to improve its readability

Question: Retrieve the appointment date and status for the appointment with ID {appointments.appointment_id}.
Evidence: The appointment ID is provided as evidence.
SQL answer: SELECT `appointment_date`, `status`
FROM `appointments`
WHERE `appointment_id` = 108;


'ni = you'